"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import invoice as shared_invoice
from sdk import utils
from typing import Optional


@dataclasses.dataclass
class PostInvoicesInvoiceIDVoidPathParams:
    
    invoice_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'invoice_id', 'style': 'simple', 'explode': False }})  
    

@dataclasses.dataclass
class PostInvoicesInvoiceIDVoidRequest:
    
    path_params: PostInvoicesInvoiceIDVoidPathParams = dataclasses.field()  
    retries: Optional[utils.RetryConfig] = dataclasses.field(default=None)  
    

@dataclasses.dataclass
class PostInvoicesInvoiceIDVoidResponse:
    
    content_type: str = dataclasses.field()  
    status_code: int = dataclasses.field()  
    invoice: Optional[shared_invoice.Invoice] = dataclasses.field(default=None)
    r"""Created"""  
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)  
    