
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-27T09:24:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf44f07c1c8158dd051fe7eb0c80669795b6131b",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
