
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <../src/include/frc2/command/ParallelRaceGroup.h>

#include <frc2/command/Command.h>
#include <frc2/command/Subsystem.h>
#include <src/helpers.h>

#define RPYGEN_DISABLE_Initialize_v
#define RPYGEN_DISABLE_Execute_v
#define RPYGEN_DISABLE_End_b
#define RPYGEN_DISABLE_IsFinished_v
#define RPYGEN_DISABLE_AddCommands_OTshared_ptr_Command__


#include <rpygen/frc2__CommandGroupBase.hpp>

namespace rpygen {

using namespace frc2;


template <typename CfgBase>
using PyTrampolineCfgBase_frc2__ParallelRaceGroup =
    PyTrampolineCfg_frc2__CommandGroupBase<
CfgBase
>;

template <typename CfgBase = EmptyTrampolineCfg>
struct PyTrampolineCfg_frc2__ParallelRaceGroup :
    PyTrampolineCfgBase_frc2__ParallelRaceGroup< CfgBase>
{
    using Base = frc2::ParallelRaceGroup;

    using override_base_KRunsWhenDisabled_v = frc2::ParallelRaceGroup;
    using override_base_KGetInterruptionBehavior_v = frc2::ParallelRaceGroup;
};


template <typename PyTrampolineBase, typename PyTrampolineCfg>
using PyTrampolineBase_frc2__ParallelRaceGroup =
    PyTrampoline_frc2__CommandGroupBase<
        PyTrampolineBase
        
        , PyTrampolineCfg
    >
;

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_frc2__ParallelRaceGroup : PyTrampolineBase_frc2__ParallelRaceGroup<PyTrampolineBase, PyTrampolineCfg> {
    using PyTrampolineBase_frc2__ParallelRaceGroup<PyTrampolineBase, PyTrampolineCfg>::PyTrampolineBase_frc2__ParallelRaceGroup;



#ifndef RPYGEN_DISABLE_KRunsWhenDisabled_v
    bool RunsWhenDisabled() const override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_KRunsWhenDisabled_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(bool), LookupBase,
            "runsWhenDisabled", );
        return CxxCallBase::RunsWhenDisabled();
    }
#endif

#ifndef RPYGEN_DISABLE_KGetInterruptionBehavior_v
    Command::InterruptionBehavior GetInterruptionBehavior() const override {
        using LookupBase = typename PyTrampolineCfg::Base;
        using CxxCallBase = typename PyTrampolineCfg::override_base_KGetInterruptionBehavior_v;
        PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(Command::InterruptionBehavior), LookupBase,
            "getInterruptionBehavior", );
        return CxxCallBase::GetInterruptionBehavior();
    }
#endif




};

}; // namespace rpygen
