# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EquipmentPressureTestData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'com': 'str',
        'des': 'str',
        'dttm': 'datetime',
        'dttmnexttest': 'datetime',
        'failflag': 'bool',
        'fluiddensity': 'float',
        'idrec': 'str',
        'idrecjob': 'str',
        'idrectestitem': 'str',
        'idwell': 'str',
        'operator': 'str',
        'presrefmeasure': 'str',
        'refnochart': 'str',
        'testfluidtyp': 'str',
        'testsubtyp': 'str',
        'testtyp': 'str',
        'usernum1': 'float',
        'usernum2': 'float',
        'usernum3': 'float',
        'usertxt1': 'str',
        'vollost': 'float',
        'volpumped': 'float',
        'wellpresused': 'bool',
        'systag': 'str'
    }

    attribute_map = {
        'com': 'com',
        'des': 'des',
        'dttm': 'dttm',
        'dttmnexttest': 'dttmnexttest',
        'failflag': 'failflag',
        'fluiddensity': 'fluiddensity',
        'idrec': 'idrec',
        'idrecjob': 'idrecjob',
        'idrectestitem': 'idrectestitem',
        'idwell': 'idwell',
        'operator': 'operator',
        'presrefmeasure': 'presrefmeasure',
        'refnochart': 'refnochart',
        'testfluidtyp': 'testfluidtyp',
        'testsubtyp': 'testsubtyp',
        'testtyp': 'testtyp',
        'usernum1': 'usernum1',
        'usernum2': 'usernum2',
        'usernum3': 'usernum3',
        'usertxt1': 'usertxt1',
        'vollost': 'vollost',
        'volpumped': 'volpumped',
        'wellpresused': 'wellpresused',
        'systag': 'systag'
    }

    def __init__(self, com=None, des=None, dttm=None, dttmnexttest=None, failflag=None, fluiddensity=None, idrec=None, idrecjob=None, idrectestitem=None, idwell=None, operator=None, presrefmeasure=None, refnochart=None, testfluidtyp=None, testsubtyp=None, testtyp=None, usernum1=None, usernum2=None, usernum3=None, usertxt1=None, vollost=None, volpumped=None, wellpresused=None, systag=None):  # noqa: E501
        """EquipmentPressureTestData - a model defined in Swagger"""  # noqa: E501
        self._com = None
        self._des = None
        self._dttm = None
        self._dttmnexttest = None
        self._failflag = None
        self._fluiddensity = None
        self._idrec = None
        self._idrecjob = None
        self._idrectestitem = None
        self._idwell = None
        self._operator = None
        self._presrefmeasure = None
        self._refnochart = None
        self._testfluidtyp = None
        self._testsubtyp = None
        self._testtyp = None
        self._usernum1 = None
        self._usernum2 = None
        self._usernum3 = None
        self._usertxt1 = None
        self._vollost = None
        self._volpumped = None
        self._wellpresused = None
        self._systag = None
        self.discriminator = None
        if com is not None:
            self.com = com
        if des is not None:
            self.des = des
        if dttm is not None:
            self.dttm = dttm
        if dttmnexttest is not None:
            self.dttmnexttest = dttmnexttest
        if failflag is not None:
            self.failflag = failflag
        if fluiddensity is not None:
            self.fluiddensity = fluiddensity
        if idrec is not None:
            self.idrec = idrec
        if idrecjob is not None:
            self.idrecjob = idrecjob
        if idrectestitem is not None:
            self.idrectestitem = idrectestitem
        self.idwell = idwell
        if operator is not None:
            self.operator = operator
        if presrefmeasure is not None:
            self.presrefmeasure = presrefmeasure
        if refnochart is not None:
            self.refnochart = refnochart
        if testfluidtyp is not None:
            self.testfluidtyp = testfluidtyp
        if testsubtyp is not None:
            self.testsubtyp = testsubtyp
        if testtyp is not None:
            self.testtyp = testtyp
        if usernum1 is not None:
            self.usernum1 = usernum1
        if usernum2 is not None:
            self.usernum2 = usernum2
        if usernum3 is not None:
            self.usernum3 = usernum3
        if usertxt1 is not None:
            self.usertxt1 = usertxt1
        if vollost is not None:
            self.vollost = vollost
        if volpumped is not None:
            self.volpumped = volpumped
        if wellpresused is not None:
            self.wellpresused = wellpresused
        if systag is not None:
            self.systag = systag

    @property
    def com(self):
        """Gets the com of this EquipmentPressureTestData.  # noqa: E501


        :return: The com of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._com

    @com.setter
    def com(self, com):
        """Sets the com of this EquipmentPressureTestData.


        :param com: The com of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """

        self._com = com

    @property
    def des(self):
        """Gets the des of this EquipmentPressureTestData.  # noqa: E501


        :return: The des of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._des

    @des.setter
    def des(self, des):
        """Sets the des of this EquipmentPressureTestData.


        :param des: The des of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """

        self._des = des

    @property
    def dttm(self):
        """Gets the dttm of this EquipmentPressureTestData.  # noqa: E501


        :return: The dttm of this EquipmentPressureTestData.  # noqa: E501
        :rtype: datetime
        """
        return self._dttm

    @dttm.setter
    def dttm(self, dttm):
        """Sets the dttm of this EquipmentPressureTestData.


        :param dttm: The dttm of this EquipmentPressureTestData.  # noqa: E501
        :type: datetime
        """

        self._dttm = dttm

    @property
    def dttmnexttest(self):
        """Gets the dttmnexttest of this EquipmentPressureTestData.  # noqa: E501


        :return: The dttmnexttest of this EquipmentPressureTestData.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmnexttest

    @dttmnexttest.setter
    def dttmnexttest(self, dttmnexttest):
        """Sets the dttmnexttest of this EquipmentPressureTestData.


        :param dttmnexttest: The dttmnexttest of this EquipmentPressureTestData.  # noqa: E501
        :type: datetime
        """

        self._dttmnexttest = dttmnexttest

    @property
    def failflag(self):
        """Gets the failflag of this EquipmentPressureTestData.  # noqa: E501


        :return: The failflag of this EquipmentPressureTestData.  # noqa: E501
        :rtype: bool
        """
        return self._failflag

    @failflag.setter
    def failflag(self, failflag):
        """Sets the failflag of this EquipmentPressureTestData.


        :param failflag: The failflag of this EquipmentPressureTestData.  # noqa: E501
        :type: bool
        """

        self._failflag = failflag

    @property
    def fluiddensity(self):
        """Gets the fluiddensity of this EquipmentPressureTestData.  # noqa: E501


        :return: The fluiddensity of this EquipmentPressureTestData.  # noqa: E501
        :rtype: float
        """
        return self._fluiddensity

    @fluiddensity.setter
    def fluiddensity(self, fluiddensity):
        """Sets the fluiddensity of this EquipmentPressureTestData.


        :param fluiddensity: The fluiddensity of this EquipmentPressureTestData.  # noqa: E501
        :type: float
        """

        self._fluiddensity = fluiddensity

    @property
    def idrec(self):
        """Gets the idrec of this EquipmentPressureTestData.  # noqa: E501

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :return: The idrec of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this EquipmentPressureTestData.

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :param idrec: The idrec of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idrecjob(self):
        """Gets the idrecjob of this EquipmentPressureTestData.  # noqa: E501


        :return: The idrecjob of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._idrecjob

    @idrecjob.setter
    def idrecjob(self, idrecjob):
        """Sets the idrecjob of this EquipmentPressureTestData.


        :param idrecjob: The idrecjob of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """

        self._idrecjob = idrecjob

    @property
    def idrectestitem(self):
        """Gets the idrectestitem of this EquipmentPressureTestData.  # noqa: E501


        :return: The idrectestitem of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._idrectestitem

    @idrectestitem.setter
    def idrectestitem(self, idrectestitem):
        """Sets the idrectestitem of this EquipmentPressureTestData.


        :param idrectestitem: The idrectestitem of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """

        self._idrectestitem = idrectestitem

    @property
    def idwell(self):
        """Gets the idwell of this EquipmentPressureTestData.  # noqa: E501

        id of well  # noqa: E501

        :return: The idwell of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this EquipmentPressureTestData.

        id of well  # noqa: E501

        :param idwell: The idwell of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """
        if idwell is None:
            raise ValueError("Invalid value for `idwell`, must not be `None`")  # noqa: E501

        self._idwell = idwell

    @property
    def operator(self):
        """Gets the operator of this EquipmentPressureTestData.  # noqa: E501


        :return: The operator of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._operator

    @operator.setter
    def operator(self, operator):
        """Sets the operator of this EquipmentPressureTestData.


        :param operator: The operator of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """

        self._operator = operator

    @property
    def presrefmeasure(self):
        """Gets the presrefmeasure of this EquipmentPressureTestData.  # noqa: E501


        :return: The presrefmeasure of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._presrefmeasure

    @presrefmeasure.setter
    def presrefmeasure(self, presrefmeasure):
        """Sets the presrefmeasure of this EquipmentPressureTestData.


        :param presrefmeasure: The presrefmeasure of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """

        self._presrefmeasure = presrefmeasure

    @property
    def refnochart(self):
        """Gets the refnochart of this EquipmentPressureTestData.  # noqa: E501


        :return: The refnochart of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._refnochart

    @refnochart.setter
    def refnochart(self, refnochart):
        """Sets the refnochart of this EquipmentPressureTestData.


        :param refnochart: The refnochart of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """

        self._refnochart = refnochart

    @property
    def testfluidtyp(self):
        """Gets the testfluidtyp of this EquipmentPressureTestData.  # noqa: E501


        :return: The testfluidtyp of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._testfluidtyp

    @testfluidtyp.setter
    def testfluidtyp(self, testfluidtyp):
        """Sets the testfluidtyp of this EquipmentPressureTestData.


        :param testfluidtyp: The testfluidtyp of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """

        self._testfluidtyp = testfluidtyp

    @property
    def testsubtyp(self):
        """Gets the testsubtyp of this EquipmentPressureTestData.  # noqa: E501


        :return: The testsubtyp of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._testsubtyp

    @testsubtyp.setter
    def testsubtyp(self, testsubtyp):
        """Sets the testsubtyp of this EquipmentPressureTestData.


        :param testsubtyp: The testsubtyp of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """

        self._testsubtyp = testsubtyp

    @property
    def testtyp(self):
        """Gets the testtyp of this EquipmentPressureTestData.  # noqa: E501


        :return: The testtyp of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._testtyp

    @testtyp.setter
    def testtyp(self, testtyp):
        """Sets the testtyp of this EquipmentPressureTestData.


        :param testtyp: The testtyp of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """

        self._testtyp = testtyp

    @property
    def usernum1(self):
        """Gets the usernum1 of this EquipmentPressureTestData.  # noqa: E501


        :return: The usernum1 of this EquipmentPressureTestData.  # noqa: E501
        :rtype: float
        """
        return self._usernum1

    @usernum1.setter
    def usernum1(self, usernum1):
        """Sets the usernum1 of this EquipmentPressureTestData.


        :param usernum1: The usernum1 of this EquipmentPressureTestData.  # noqa: E501
        :type: float
        """

        self._usernum1 = usernum1

    @property
    def usernum2(self):
        """Gets the usernum2 of this EquipmentPressureTestData.  # noqa: E501


        :return: The usernum2 of this EquipmentPressureTestData.  # noqa: E501
        :rtype: float
        """
        return self._usernum2

    @usernum2.setter
    def usernum2(self, usernum2):
        """Sets the usernum2 of this EquipmentPressureTestData.


        :param usernum2: The usernum2 of this EquipmentPressureTestData.  # noqa: E501
        :type: float
        """

        self._usernum2 = usernum2

    @property
    def usernum3(self):
        """Gets the usernum3 of this EquipmentPressureTestData.  # noqa: E501


        :return: The usernum3 of this EquipmentPressureTestData.  # noqa: E501
        :rtype: float
        """
        return self._usernum3

    @usernum3.setter
    def usernum3(self, usernum3):
        """Sets the usernum3 of this EquipmentPressureTestData.


        :param usernum3: The usernum3 of this EquipmentPressureTestData.  # noqa: E501
        :type: float
        """

        self._usernum3 = usernum3

    @property
    def usertxt1(self):
        """Gets the usertxt1 of this EquipmentPressureTestData.  # noqa: E501


        :return: The usertxt1 of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._usertxt1

    @usertxt1.setter
    def usertxt1(self, usertxt1):
        """Sets the usertxt1 of this EquipmentPressureTestData.


        :param usertxt1: The usertxt1 of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """

        self._usertxt1 = usertxt1

    @property
    def vollost(self):
        """Gets the vollost of this EquipmentPressureTestData.  # noqa: E501


        :return: The vollost of this EquipmentPressureTestData.  # noqa: E501
        :rtype: float
        """
        return self._vollost

    @vollost.setter
    def vollost(self, vollost):
        """Sets the vollost of this EquipmentPressureTestData.


        :param vollost: The vollost of this EquipmentPressureTestData.  # noqa: E501
        :type: float
        """

        self._vollost = vollost

    @property
    def volpumped(self):
        """Gets the volpumped of this EquipmentPressureTestData.  # noqa: E501


        :return: The volpumped of this EquipmentPressureTestData.  # noqa: E501
        :rtype: float
        """
        return self._volpumped

    @volpumped.setter
    def volpumped(self, volpumped):
        """Sets the volpumped of this EquipmentPressureTestData.


        :param volpumped: The volpumped of this EquipmentPressureTestData.  # noqa: E501
        :type: float
        """

        self._volpumped = volpumped

    @property
    def wellpresused(self):
        """Gets the wellpresused of this EquipmentPressureTestData.  # noqa: E501


        :return: The wellpresused of this EquipmentPressureTestData.  # noqa: E501
        :rtype: bool
        """
        return self._wellpresused

    @wellpresused.setter
    def wellpresused(self, wellpresused):
        """Sets the wellpresused of this EquipmentPressureTestData.


        :param wellpresused: The wellpresused of this EquipmentPressureTestData.  # noqa: E501
        :type: bool
        """

        self._wellpresused = wellpresused

    @property
    def systag(self):
        """Gets the systag of this EquipmentPressureTestData.  # noqa: E501


        :return: The systag of this EquipmentPressureTestData.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this EquipmentPressureTestData.


        :param systag: The systag of this EquipmentPressureTestData.  # noqa: E501
        :type: str
        """

        self._systag = systag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EquipmentPressureTestData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EquipmentPressureTestData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
