# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PackerData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'elastomerhardnessdes': 'str',
        'elastomertyp': 'str',
        'elemcenter': 'float',
        'idrec': 'str',
        'idrecparent': 'str',
        'idwell': 'str',
        'lenpolishbore': 'float',
        'penetratortyp': 'str',
        'presdiffmax': 'float',
        'retrievable': 'bool',
        'retrievemeth': 'str',
        'setfluidtyp': 'str',
        'setmech': 'str',
        'setprocedure': 'str',
        'shearrelease': 'float',
        'slips': 'str',
        'szpolishbore': 'float',
        'unsettingprocedure': 'str',
        'systag': 'str'
    }

    attribute_map = {
        'elastomerhardnessdes': 'elastomerhardnessdes',
        'elastomertyp': 'elastomertyp',
        'elemcenter': 'elemcenter',
        'idrec': 'idrec',
        'idrecparent': 'idrecparent',
        'idwell': 'idwell',
        'lenpolishbore': 'lenpolishbore',
        'penetratortyp': 'penetratortyp',
        'presdiffmax': 'presdiffmax',
        'retrievable': 'retrievable',
        'retrievemeth': 'retrievemeth',
        'setfluidtyp': 'setfluidtyp',
        'setmech': 'setmech',
        'setprocedure': 'setprocedure',
        'shearrelease': 'shearrelease',
        'slips': 'slips',
        'szpolishbore': 'szpolishbore',
        'unsettingprocedure': 'unsettingprocedure',
        'systag': 'systag'
    }

    def __init__(self, elastomerhardnessdes=None, elastomertyp=None, elemcenter=None, idrec=None, idrecparent=None, idwell=None, lenpolishbore=None, penetratortyp=None, presdiffmax=None, retrievable=None, retrievemeth=None, setfluidtyp=None, setmech=None, setprocedure=None, shearrelease=None, slips=None, szpolishbore=None, unsettingprocedure=None, systag=None):  # noqa: E501
        """PackerData - a model defined in Swagger"""  # noqa: E501
        self._elastomerhardnessdes = None
        self._elastomertyp = None
        self._elemcenter = None
        self._idrec = None
        self._idrecparent = None
        self._idwell = None
        self._lenpolishbore = None
        self._penetratortyp = None
        self._presdiffmax = None
        self._retrievable = None
        self._retrievemeth = None
        self._setfluidtyp = None
        self._setmech = None
        self._setprocedure = None
        self._shearrelease = None
        self._slips = None
        self._szpolishbore = None
        self._unsettingprocedure = None
        self._systag = None
        self.discriminator = None
        if elastomerhardnessdes is not None:
            self.elastomerhardnessdes = elastomerhardnessdes
        if elastomertyp is not None:
            self.elastomertyp = elastomertyp
        if elemcenter is not None:
            self.elemcenter = elemcenter
        if idrec is not None:
            self.idrec = idrec
        self.idrecparent = idrecparent
        self.idwell = idwell
        if lenpolishbore is not None:
            self.lenpolishbore = lenpolishbore
        if penetratortyp is not None:
            self.penetratortyp = penetratortyp
        if presdiffmax is not None:
            self.presdiffmax = presdiffmax
        if retrievable is not None:
            self.retrievable = retrievable
        if retrievemeth is not None:
            self.retrievemeth = retrievemeth
        if setfluidtyp is not None:
            self.setfluidtyp = setfluidtyp
        if setmech is not None:
            self.setmech = setmech
        if setprocedure is not None:
            self.setprocedure = setprocedure
        if shearrelease is not None:
            self.shearrelease = shearrelease
        if slips is not None:
            self.slips = slips
        if szpolishbore is not None:
            self.szpolishbore = szpolishbore
        if unsettingprocedure is not None:
            self.unsettingprocedure = unsettingprocedure
        if systag is not None:
            self.systag = systag

    @property
    def elastomerhardnessdes(self):
        """Gets the elastomerhardnessdes of this PackerData.  # noqa: E501


        :return: The elastomerhardnessdes of this PackerData.  # noqa: E501
        :rtype: str
        """
        return self._elastomerhardnessdes

    @elastomerhardnessdes.setter
    def elastomerhardnessdes(self, elastomerhardnessdes):
        """Sets the elastomerhardnessdes of this PackerData.


        :param elastomerhardnessdes: The elastomerhardnessdes of this PackerData.  # noqa: E501
        :type: str
        """

        self._elastomerhardnessdes = elastomerhardnessdes

    @property
    def elastomertyp(self):
        """Gets the elastomertyp of this PackerData.  # noqa: E501


        :return: The elastomertyp of this PackerData.  # noqa: E501
        :rtype: str
        """
        return self._elastomertyp

    @elastomertyp.setter
    def elastomertyp(self, elastomertyp):
        """Sets the elastomertyp of this PackerData.


        :param elastomertyp: The elastomertyp of this PackerData.  # noqa: E501
        :type: str
        """

        self._elastomertyp = elastomertyp

    @property
    def elemcenter(self):
        """Gets the elemcenter of this PackerData.  # noqa: E501


        :return: The elemcenter of this PackerData.  # noqa: E501
        :rtype: float
        """
        return self._elemcenter

    @elemcenter.setter
    def elemcenter(self, elemcenter):
        """Sets the elemcenter of this PackerData.


        :param elemcenter: The elemcenter of this PackerData.  # noqa: E501
        :type: float
        """

        self._elemcenter = elemcenter

    @property
    def idrec(self):
        """Gets the idrec of this PackerData.  # noqa: E501

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :return: The idrec of this PackerData.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this PackerData.

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :param idrec: The idrec of this PackerData.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idrecparent(self):
        """Gets the idrecparent of this PackerData.  # noqa: E501

        id of parrent table  # noqa: E501

        :return: The idrecparent of this PackerData.  # noqa: E501
        :rtype: str
        """
        return self._idrecparent

    @idrecparent.setter
    def idrecparent(self, idrecparent):
        """Sets the idrecparent of this PackerData.

        id of parrent table  # noqa: E501

        :param idrecparent: The idrecparent of this PackerData.  # noqa: E501
        :type: str
        """
        if idrecparent is None:
            raise ValueError("Invalid value for `idrecparent`, must not be `None`")  # noqa: E501

        self._idrecparent = idrecparent

    @property
    def idwell(self):
        """Gets the idwell of this PackerData.  # noqa: E501

        id of well  # noqa: E501

        :return: The idwell of this PackerData.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this PackerData.

        id of well  # noqa: E501

        :param idwell: The idwell of this PackerData.  # noqa: E501
        :type: str
        """
        if idwell is None:
            raise ValueError("Invalid value for `idwell`, must not be `None`")  # noqa: E501

        self._idwell = idwell

    @property
    def lenpolishbore(self):
        """Gets the lenpolishbore of this PackerData.  # noqa: E501


        :return: The lenpolishbore of this PackerData.  # noqa: E501
        :rtype: float
        """
        return self._lenpolishbore

    @lenpolishbore.setter
    def lenpolishbore(self, lenpolishbore):
        """Sets the lenpolishbore of this PackerData.


        :param lenpolishbore: The lenpolishbore of this PackerData.  # noqa: E501
        :type: float
        """

        self._lenpolishbore = lenpolishbore

    @property
    def penetratortyp(self):
        """Gets the penetratortyp of this PackerData.  # noqa: E501


        :return: The penetratortyp of this PackerData.  # noqa: E501
        :rtype: str
        """
        return self._penetratortyp

    @penetratortyp.setter
    def penetratortyp(self, penetratortyp):
        """Sets the penetratortyp of this PackerData.


        :param penetratortyp: The penetratortyp of this PackerData.  # noqa: E501
        :type: str
        """

        self._penetratortyp = penetratortyp

    @property
    def presdiffmax(self):
        """Gets the presdiffmax of this PackerData.  # noqa: E501


        :return: The presdiffmax of this PackerData.  # noqa: E501
        :rtype: float
        """
        return self._presdiffmax

    @presdiffmax.setter
    def presdiffmax(self, presdiffmax):
        """Sets the presdiffmax of this PackerData.


        :param presdiffmax: The presdiffmax of this PackerData.  # noqa: E501
        :type: float
        """

        self._presdiffmax = presdiffmax

    @property
    def retrievable(self):
        """Gets the retrievable of this PackerData.  # noqa: E501


        :return: The retrievable of this PackerData.  # noqa: E501
        :rtype: bool
        """
        return self._retrievable

    @retrievable.setter
    def retrievable(self, retrievable):
        """Sets the retrievable of this PackerData.


        :param retrievable: The retrievable of this PackerData.  # noqa: E501
        :type: bool
        """

        self._retrievable = retrievable

    @property
    def retrievemeth(self):
        """Gets the retrievemeth of this PackerData.  # noqa: E501


        :return: The retrievemeth of this PackerData.  # noqa: E501
        :rtype: str
        """
        return self._retrievemeth

    @retrievemeth.setter
    def retrievemeth(self, retrievemeth):
        """Sets the retrievemeth of this PackerData.


        :param retrievemeth: The retrievemeth of this PackerData.  # noqa: E501
        :type: str
        """

        self._retrievemeth = retrievemeth

    @property
    def setfluidtyp(self):
        """Gets the setfluidtyp of this PackerData.  # noqa: E501


        :return: The setfluidtyp of this PackerData.  # noqa: E501
        :rtype: str
        """
        return self._setfluidtyp

    @setfluidtyp.setter
    def setfluidtyp(self, setfluidtyp):
        """Sets the setfluidtyp of this PackerData.


        :param setfluidtyp: The setfluidtyp of this PackerData.  # noqa: E501
        :type: str
        """

        self._setfluidtyp = setfluidtyp

    @property
    def setmech(self):
        """Gets the setmech of this PackerData.  # noqa: E501


        :return: The setmech of this PackerData.  # noqa: E501
        :rtype: str
        """
        return self._setmech

    @setmech.setter
    def setmech(self, setmech):
        """Sets the setmech of this PackerData.


        :param setmech: The setmech of this PackerData.  # noqa: E501
        :type: str
        """

        self._setmech = setmech

    @property
    def setprocedure(self):
        """Gets the setprocedure of this PackerData.  # noqa: E501


        :return: The setprocedure of this PackerData.  # noqa: E501
        :rtype: str
        """
        return self._setprocedure

    @setprocedure.setter
    def setprocedure(self, setprocedure):
        """Sets the setprocedure of this PackerData.


        :param setprocedure: The setprocedure of this PackerData.  # noqa: E501
        :type: str
        """

        self._setprocedure = setprocedure

    @property
    def shearrelease(self):
        """Gets the shearrelease of this PackerData.  # noqa: E501


        :return: The shearrelease of this PackerData.  # noqa: E501
        :rtype: float
        """
        return self._shearrelease

    @shearrelease.setter
    def shearrelease(self, shearrelease):
        """Sets the shearrelease of this PackerData.


        :param shearrelease: The shearrelease of this PackerData.  # noqa: E501
        :type: float
        """

        self._shearrelease = shearrelease

    @property
    def slips(self):
        """Gets the slips of this PackerData.  # noqa: E501


        :return: The slips of this PackerData.  # noqa: E501
        :rtype: str
        """
        return self._slips

    @slips.setter
    def slips(self, slips):
        """Sets the slips of this PackerData.


        :param slips: The slips of this PackerData.  # noqa: E501
        :type: str
        """

        self._slips = slips

    @property
    def szpolishbore(self):
        """Gets the szpolishbore of this PackerData.  # noqa: E501


        :return: The szpolishbore of this PackerData.  # noqa: E501
        :rtype: float
        """
        return self._szpolishbore

    @szpolishbore.setter
    def szpolishbore(self, szpolishbore):
        """Sets the szpolishbore of this PackerData.


        :param szpolishbore: The szpolishbore of this PackerData.  # noqa: E501
        :type: float
        """

        self._szpolishbore = szpolishbore

    @property
    def unsettingprocedure(self):
        """Gets the unsettingprocedure of this PackerData.  # noqa: E501


        :return: The unsettingprocedure of this PackerData.  # noqa: E501
        :rtype: str
        """
        return self._unsettingprocedure

    @unsettingprocedure.setter
    def unsettingprocedure(self, unsettingprocedure):
        """Sets the unsettingprocedure of this PackerData.


        :param unsettingprocedure: The unsettingprocedure of this PackerData.  # noqa: E501
        :type: str
        """

        self._unsettingprocedure = unsettingprocedure

    @property
    def systag(self):
        """Gets the systag of this PackerData.  # noqa: E501


        :return: The systag of this PackerData.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this PackerData.


        :param systag: The systag of this PackerData.  # noqa: E501
        :type: str
        """

        self._systag = systag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PackerData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PackerData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
