"""
    Koverse Data Platform (KDP) API

    The KDP API is a REST API that can be used to create, access, and update data in KDP Workspaces  # noqa: E501

    The version of the OpenAPI document: 4.53.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import kdp_api
from kdp_api.model.workspace_invitation import WorkspaceInvitation
globals()['WorkspaceInvitation'] = WorkspaceInvitation
from kdp_api.model.workspace_invitation_list import WorkspaceInvitationList


class TestWorkspaceInvitationList(unittest.TestCase):
    """WorkspaceInvitationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspaceInvitationList(self):
        """Test WorkspaceInvitationList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkspaceInvitationList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
