# Generated by Django 4.0 on 2022-09-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_remove_area_study_program_delete_faculty_delete_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echelon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
