# Generated by Django 3.2 on 2022-12-09 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0011_alter_unit_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.de'),
        ),
    ]
