# to be generated at package build time
#
# application_paths = {
#     'assistant': 'assistant.exe',
#     'canbusutil': 'canbusutil.exe',
#     ...
# }
application_paths = {
    'assistant': 'Assistant.app',
    'designer': 'Designer.app',
    'linguist': 'Linguist.app',
    'androiddeployqt': 'androiddeployqt',
    'androidtestrunner': 'androidtestrunner',
    'lconvert': 'lconvert',
    'lrelease': 'lrelease',
    'lupdate': 'lupdate',
    'macdeployqt': 'macdeployqt',
    'pixeltool': 'pixeltool.app',
    'qdbus': 'qdbus',
    'qdbuscpp2xml': 'qdbuscpp2xml',
    'qdbusviewer': 'qdbusviewer.app',
    'qdbusxml2cpp': 'qdbusxml2cpp',
    'qdistancefieldgenerator': 'qdistancefieldgenerator',
    'qdoc': 'qdoc',
    'qmake': 'qmake',
    'qmake6': 'qmake6',
    'qml': 'qml',
    'qmldom': 'qmldom',
    'qmleasing': 'qmleasing',
    'qmlformat': 'qmlformat',
    'qmllint': 'qmllint',
    'qmlls': 'qmlls',
    'qmlplugindump': 'qmlplugindump',
    'qmlpreview': 'qmlpreview',
    'qmlprofiler': 'qmlprofiler',
    'qmlscene': 'qmlscene',
    'qmltc': 'qmltc',
    'qmltestrunner': 'qmltestrunner',
    'qmltime': 'qmltime',
    'qt-cmake': 'qt-cmake',
    'qt-cmake-private': 'qt-cmake-private',
    'qt-cmake-standalone-test': 'qt-cmake-standalone-test',
    'qt-configure-module': 'qt-configure-module',
    'qtdiag': 'qtdiag',
    'qtdiag6': 'qtdiag6',
    'qtpaths': 'qtpaths',
    'qtpaths6': 'qtpaths6',
    'qtplugininfo': 'qtplugininfo',
}
