
WHITESPACE         = ' \n\t'
DIGITS             = '0987654321'
LOWERCASES         = 'abcdefghijklmnopqrstuvwxyz'
UPPERCASES         = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
CHARS              = UPPERCASES + LOWERCASES
CHARACTERS         = '{}_^=.:'
OBJECT_CHARACTERS  = CHARACTERS + UPPERCASES + LOWERCASES + DIGITS

re_float            = '^(\d+)(\.)(\d+)$'
re_integer          = '^(\d+)$'
re_integral         = '^(integrate)$'
re_diff             = '^(diff)$'
re_solve            = '^(solve)$'
re_simplify         = '^(simplify)$'
re_expand           = '^(expand)$'
re_limit            = '^(limit)$'
re_series           = '^(series)$'
re_numerical        = '^(numerical)$'
re_plot             = '^(plot)$'
re_sin              = '^(sin)$'
re_cos              = '^(cos)$'
re_tan              = '^(tan)$'
re_sinh             = '^(sinh)$'
re_cosh             = '^(cosh)$'
re_tanh             = '^(tanh)$'
re_asin             = '^(asin)$'
re_acos             = '^(acos)$'
re_atan             = '^(atan)$'
re_asinh            = '^(asinh)$'
re_acosh            = '^(acosh)$'
re_atanh            = '^(atanh)$'
re_exp              = '^(exp)$'
re_pi               = '^(PI)$|^(pi)$'
re_e                = '^(E)$|^(e)$'
re_variable         = '^([a-zA-Z]+)$|^(([a-zA-Z]+)(\_)([0-9]+|[a-zA-Z]+))$'