# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DrillingParameterData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bhaanpres': 'float',
        'bhtemp': 'float',
        'depthend': 'float',
        'depthstart': 'float',
        'dttmend': 'datetime',
        'dttmstart': 'datetime',
        'ecdendoverride': 'float',
        'excludefromnewhole': 'bool',
        'gasinjrate': 'float',
        'gasreturnrate': 'float',
        'hookloadoffbottom': 'float',
        'hookloadpickup': 'float',
        'hookloadrotating': 'float',
        'hookloadslackoff': 'float',
        'idrec': 'str',
        'idrecparent': 'str',
        'idrecwellbore': 'str',
        'idwell': 'str',
        'injtemp': 'float',
        'liquidinjrate': 'float',
        'liquidinjrateriser': 'float',
        'liquidreturnrate': 'float',
        'note': 'str',
        'refnostand': 'str',
        'ropinst': 'float',
        'rpmmotor': 'float',
        'rpmstring': 'float',
        'sppdiff': 'float',
        'sppdrill': 'float',
        'surfannpres': 'float',
        'surfanntemp': 'float',
        'szodvgstab': 'float',
        'tfo': 'float',
        'tforef': 'str',
        'tmcirc': 'float',
        'tmdrill': 'float',
        'tmother': 'float',
        'tmtrip': 'float',
        'torquedrill': 'float',
        'torqueoffbtm': 'float',
        'torqueunits': 'str',
        'typ1': 'str',
        'typ2': 'str',
        'wob': 'float',
        'systag': 'str'
    }

    attribute_map = {
        'bhaanpres': 'bhaanpres',
        'bhtemp': 'bhtemp',
        'depthend': 'depthend',
        'depthstart': 'depthstart',
        'dttmend': 'dttmend',
        'dttmstart': 'dttmstart',
        'ecdendoverride': 'ecdendoverride',
        'excludefromnewhole': 'excludefromnewhole',
        'gasinjrate': 'gasinjrate',
        'gasreturnrate': 'gasreturnrate',
        'hookloadoffbottom': 'hookloadoffbottom',
        'hookloadpickup': 'hookloadpickup',
        'hookloadrotating': 'hookloadrotating',
        'hookloadslackoff': 'hookloadslackoff',
        'idrec': 'idrec',
        'idrecparent': 'idrecparent',
        'idrecwellbore': 'idrecwellbore',
        'idwell': 'idwell',
        'injtemp': 'injtemp',
        'liquidinjrate': 'liquidinjrate',
        'liquidinjrateriser': 'liquidinjrateriser',
        'liquidreturnrate': 'liquidreturnrate',
        'note': 'note',
        'refnostand': 'refnostand',
        'ropinst': 'ropinst',
        'rpmmotor': 'rpmmotor',
        'rpmstring': 'rpmstring',
        'sppdiff': 'sppdiff',
        'sppdrill': 'sppdrill',
        'surfannpres': 'surfannpres',
        'surfanntemp': 'surfanntemp',
        'szodvgstab': 'szodvgstab',
        'tfo': 'tfo',
        'tforef': 'tforef',
        'tmcirc': 'tmcirc',
        'tmdrill': 'tmdrill',
        'tmother': 'tmother',
        'tmtrip': 'tmtrip',
        'torquedrill': 'torquedrill',
        'torqueoffbtm': 'torqueoffbtm',
        'torqueunits': 'torqueunits',
        'typ1': 'typ1',
        'typ2': 'typ2',
        'wob': 'wob',
        'systag': 'systag'
    }

    def __init__(self, bhaanpres=None, bhtemp=None, depthend=None, depthstart=None, dttmend=None, dttmstart=None, ecdendoverride=None, excludefromnewhole=None, gasinjrate=None, gasreturnrate=None, hookloadoffbottom=None, hookloadpickup=None, hookloadrotating=None, hookloadslackoff=None, idrec=None, idrecparent=None, idrecwellbore=None, idwell=None, injtemp=None, liquidinjrate=None, liquidinjrateriser=None, liquidreturnrate=None, note=None, refnostand=None, ropinst=None, rpmmotor=None, rpmstring=None, sppdiff=None, sppdrill=None, surfannpres=None, surfanntemp=None, szodvgstab=None, tfo=None, tforef=None, tmcirc=None, tmdrill=None, tmother=None, tmtrip=None, torquedrill=None, torqueoffbtm=None, torqueunits=None, typ1=None, typ2=None, wob=None, systag=None):  # noqa: E501
        """DrillingParameterData - a model defined in Swagger"""  # noqa: E501
        self._bhaanpres = None
        self._bhtemp = None
        self._depthend = None
        self._depthstart = None
        self._dttmend = None
        self._dttmstart = None
        self._ecdendoverride = None
        self._excludefromnewhole = None
        self._gasinjrate = None
        self._gasreturnrate = None
        self._hookloadoffbottom = None
        self._hookloadpickup = None
        self._hookloadrotating = None
        self._hookloadslackoff = None
        self._idrec = None
        self._idrecparent = None
        self._idrecwellbore = None
        self._idwell = None
        self._injtemp = None
        self._liquidinjrate = None
        self._liquidinjrateriser = None
        self._liquidreturnrate = None
        self._note = None
        self._refnostand = None
        self._ropinst = None
        self._rpmmotor = None
        self._rpmstring = None
        self._sppdiff = None
        self._sppdrill = None
        self._surfannpres = None
        self._surfanntemp = None
        self._szodvgstab = None
        self._tfo = None
        self._tforef = None
        self._tmcirc = None
        self._tmdrill = None
        self._tmother = None
        self._tmtrip = None
        self._torquedrill = None
        self._torqueoffbtm = None
        self._torqueunits = None
        self._typ1 = None
        self._typ2 = None
        self._wob = None
        self._systag = None
        self.discriminator = None
        if bhaanpres is not None:
            self.bhaanpres = bhaanpres
        if bhtemp is not None:
            self.bhtemp = bhtemp
        if depthend is not None:
            self.depthend = depthend
        if depthstart is not None:
            self.depthstart = depthstart
        if dttmend is not None:
            self.dttmend = dttmend
        if dttmstart is not None:
            self.dttmstart = dttmstart
        if ecdendoverride is not None:
            self.ecdendoverride = ecdendoverride
        if excludefromnewhole is not None:
            self.excludefromnewhole = excludefromnewhole
        if gasinjrate is not None:
            self.gasinjrate = gasinjrate
        if gasreturnrate is not None:
            self.gasreturnrate = gasreturnrate
        if hookloadoffbottom is not None:
            self.hookloadoffbottom = hookloadoffbottom
        if hookloadpickup is not None:
            self.hookloadpickup = hookloadpickup
        if hookloadrotating is not None:
            self.hookloadrotating = hookloadrotating
        if hookloadslackoff is not None:
            self.hookloadslackoff = hookloadslackoff
        if idrec is not None:
            self.idrec = idrec
        self.idrecparent = idrecparent
        if idrecwellbore is not None:
            self.idrecwellbore = idrecwellbore
        self.idwell = idwell
        if injtemp is not None:
            self.injtemp = injtemp
        if liquidinjrate is not None:
            self.liquidinjrate = liquidinjrate
        if liquidinjrateriser is not None:
            self.liquidinjrateriser = liquidinjrateriser
        if liquidreturnrate is not None:
            self.liquidreturnrate = liquidreturnrate
        if note is not None:
            self.note = note
        if refnostand is not None:
            self.refnostand = refnostand
        if ropinst is not None:
            self.ropinst = ropinst
        if rpmmotor is not None:
            self.rpmmotor = rpmmotor
        if rpmstring is not None:
            self.rpmstring = rpmstring
        if sppdiff is not None:
            self.sppdiff = sppdiff
        if sppdrill is not None:
            self.sppdrill = sppdrill
        if surfannpres is not None:
            self.surfannpres = surfannpres
        if surfanntemp is not None:
            self.surfanntemp = surfanntemp
        if szodvgstab is not None:
            self.szodvgstab = szodvgstab
        if tfo is not None:
            self.tfo = tfo
        if tforef is not None:
            self.tforef = tforef
        if tmcirc is not None:
            self.tmcirc = tmcirc
        if tmdrill is not None:
            self.tmdrill = tmdrill
        if tmother is not None:
            self.tmother = tmother
        if tmtrip is not None:
            self.tmtrip = tmtrip
        if torquedrill is not None:
            self.torquedrill = torquedrill
        if torqueoffbtm is not None:
            self.torqueoffbtm = torqueoffbtm
        if torqueunits is not None:
            self.torqueunits = torqueunits
        if typ1 is not None:
            self.typ1 = typ1
        if typ2 is not None:
            self.typ2 = typ2
        if wob is not None:
            self.wob = wob
        if systag is not None:
            self.systag = systag

    @property
    def bhaanpres(self):
        """Gets the bhaanpres of this DrillingParameterData.  # noqa: E501


        :return: The bhaanpres of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._bhaanpres

    @bhaanpres.setter
    def bhaanpres(self, bhaanpres):
        """Sets the bhaanpres of this DrillingParameterData.


        :param bhaanpres: The bhaanpres of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._bhaanpres = bhaanpres

    @property
    def bhtemp(self):
        """Gets the bhtemp of this DrillingParameterData.  # noqa: E501


        :return: The bhtemp of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._bhtemp

    @bhtemp.setter
    def bhtemp(self, bhtemp):
        """Sets the bhtemp of this DrillingParameterData.


        :param bhtemp: The bhtemp of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._bhtemp = bhtemp

    @property
    def depthend(self):
        """Gets the depthend of this DrillingParameterData.  # noqa: E501


        :return: The depthend of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._depthend

    @depthend.setter
    def depthend(self, depthend):
        """Sets the depthend of this DrillingParameterData.


        :param depthend: The depthend of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._depthend = depthend

    @property
    def depthstart(self):
        """Gets the depthstart of this DrillingParameterData.  # noqa: E501


        :return: The depthstart of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._depthstart

    @depthstart.setter
    def depthstart(self, depthstart):
        """Sets the depthstart of this DrillingParameterData.


        :param depthstart: The depthstart of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._depthstart = depthstart

    @property
    def dttmend(self):
        """Gets the dttmend of this DrillingParameterData.  # noqa: E501


        :return: The dttmend of this DrillingParameterData.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmend

    @dttmend.setter
    def dttmend(self, dttmend):
        """Sets the dttmend of this DrillingParameterData.


        :param dttmend: The dttmend of this DrillingParameterData.  # noqa: E501
        :type: datetime
        """

        self._dttmend = dttmend

    @property
    def dttmstart(self):
        """Gets the dttmstart of this DrillingParameterData.  # noqa: E501


        :return: The dttmstart of this DrillingParameterData.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmstart

    @dttmstart.setter
    def dttmstart(self, dttmstart):
        """Sets the dttmstart of this DrillingParameterData.


        :param dttmstart: The dttmstart of this DrillingParameterData.  # noqa: E501
        :type: datetime
        """

        self._dttmstart = dttmstart

    @property
    def ecdendoverride(self):
        """Gets the ecdendoverride of this DrillingParameterData.  # noqa: E501


        :return: The ecdendoverride of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._ecdendoverride

    @ecdendoverride.setter
    def ecdendoverride(self, ecdendoverride):
        """Sets the ecdendoverride of this DrillingParameterData.


        :param ecdendoverride: The ecdendoverride of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._ecdendoverride = ecdendoverride

    @property
    def excludefromnewhole(self):
        """Gets the excludefromnewhole of this DrillingParameterData.  # noqa: E501


        :return: The excludefromnewhole of this DrillingParameterData.  # noqa: E501
        :rtype: bool
        """
        return self._excludefromnewhole

    @excludefromnewhole.setter
    def excludefromnewhole(self, excludefromnewhole):
        """Sets the excludefromnewhole of this DrillingParameterData.


        :param excludefromnewhole: The excludefromnewhole of this DrillingParameterData.  # noqa: E501
        :type: bool
        """

        self._excludefromnewhole = excludefromnewhole

    @property
    def gasinjrate(self):
        """Gets the gasinjrate of this DrillingParameterData.  # noqa: E501


        :return: The gasinjrate of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._gasinjrate

    @gasinjrate.setter
    def gasinjrate(self, gasinjrate):
        """Sets the gasinjrate of this DrillingParameterData.


        :param gasinjrate: The gasinjrate of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._gasinjrate = gasinjrate

    @property
    def gasreturnrate(self):
        """Gets the gasreturnrate of this DrillingParameterData.  # noqa: E501


        :return: The gasreturnrate of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._gasreturnrate

    @gasreturnrate.setter
    def gasreturnrate(self, gasreturnrate):
        """Sets the gasreturnrate of this DrillingParameterData.


        :param gasreturnrate: The gasreturnrate of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._gasreturnrate = gasreturnrate

    @property
    def hookloadoffbottom(self):
        """Gets the hookloadoffbottom of this DrillingParameterData.  # noqa: E501


        :return: The hookloadoffbottom of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._hookloadoffbottom

    @hookloadoffbottom.setter
    def hookloadoffbottom(self, hookloadoffbottom):
        """Sets the hookloadoffbottom of this DrillingParameterData.


        :param hookloadoffbottom: The hookloadoffbottom of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._hookloadoffbottom = hookloadoffbottom

    @property
    def hookloadpickup(self):
        """Gets the hookloadpickup of this DrillingParameterData.  # noqa: E501


        :return: The hookloadpickup of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._hookloadpickup

    @hookloadpickup.setter
    def hookloadpickup(self, hookloadpickup):
        """Sets the hookloadpickup of this DrillingParameterData.


        :param hookloadpickup: The hookloadpickup of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._hookloadpickup = hookloadpickup

    @property
    def hookloadrotating(self):
        """Gets the hookloadrotating of this DrillingParameterData.  # noqa: E501


        :return: The hookloadrotating of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._hookloadrotating

    @hookloadrotating.setter
    def hookloadrotating(self, hookloadrotating):
        """Sets the hookloadrotating of this DrillingParameterData.


        :param hookloadrotating: The hookloadrotating of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._hookloadrotating = hookloadrotating

    @property
    def hookloadslackoff(self):
        """Gets the hookloadslackoff of this DrillingParameterData.  # noqa: E501


        :return: The hookloadslackoff of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._hookloadslackoff

    @hookloadslackoff.setter
    def hookloadslackoff(self, hookloadslackoff):
        """Sets the hookloadslackoff of this DrillingParameterData.


        :param hookloadslackoff: The hookloadslackoff of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._hookloadslackoff = hookloadslackoff

    @property
    def idrec(self):
        """Gets the idrec of this DrillingParameterData.  # noqa: E501

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :return: The idrec of this DrillingParameterData.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this DrillingParameterData.

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :param idrec: The idrec of this DrillingParameterData.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idrecparent(self):
        """Gets the idrecparent of this DrillingParameterData.  # noqa: E501

        id of parrent table  # noqa: E501

        :return: The idrecparent of this DrillingParameterData.  # noqa: E501
        :rtype: str
        """
        return self._idrecparent

    @idrecparent.setter
    def idrecparent(self, idrecparent):
        """Sets the idrecparent of this DrillingParameterData.

        id of parrent table  # noqa: E501

        :param idrecparent: The idrecparent of this DrillingParameterData.  # noqa: E501
        :type: str
        """
        if idrecparent is None:
            raise ValueError("Invalid value for `idrecparent`, must not be `None`")  # noqa: E501

        self._idrecparent = idrecparent

    @property
    def idrecwellbore(self):
        """Gets the idrecwellbore of this DrillingParameterData.  # noqa: E501


        :return: The idrecwellbore of this DrillingParameterData.  # noqa: E501
        :rtype: str
        """
        return self._idrecwellbore

    @idrecwellbore.setter
    def idrecwellbore(self, idrecwellbore):
        """Sets the idrecwellbore of this DrillingParameterData.


        :param idrecwellbore: The idrecwellbore of this DrillingParameterData.  # noqa: E501
        :type: str
        """

        self._idrecwellbore = idrecwellbore

    @property
    def idwell(self):
        """Gets the idwell of this DrillingParameterData.  # noqa: E501

        id of well  # noqa: E501

        :return: The idwell of this DrillingParameterData.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this DrillingParameterData.

        id of well  # noqa: E501

        :param idwell: The idwell of this DrillingParameterData.  # noqa: E501
        :type: str
        """
        if idwell is None:
            raise ValueError("Invalid value for `idwell`, must not be `None`")  # noqa: E501

        self._idwell = idwell

    @property
    def injtemp(self):
        """Gets the injtemp of this DrillingParameterData.  # noqa: E501


        :return: The injtemp of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._injtemp

    @injtemp.setter
    def injtemp(self, injtemp):
        """Sets the injtemp of this DrillingParameterData.


        :param injtemp: The injtemp of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._injtemp = injtemp

    @property
    def liquidinjrate(self):
        """Gets the liquidinjrate of this DrillingParameterData.  # noqa: E501


        :return: The liquidinjrate of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._liquidinjrate

    @liquidinjrate.setter
    def liquidinjrate(self, liquidinjrate):
        """Sets the liquidinjrate of this DrillingParameterData.


        :param liquidinjrate: The liquidinjrate of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._liquidinjrate = liquidinjrate

    @property
    def liquidinjrateriser(self):
        """Gets the liquidinjrateriser of this DrillingParameterData.  # noqa: E501


        :return: The liquidinjrateriser of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._liquidinjrateriser

    @liquidinjrateriser.setter
    def liquidinjrateriser(self, liquidinjrateriser):
        """Sets the liquidinjrateriser of this DrillingParameterData.


        :param liquidinjrateriser: The liquidinjrateriser of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._liquidinjrateriser = liquidinjrateriser

    @property
    def liquidreturnrate(self):
        """Gets the liquidreturnrate of this DrillingParameterData.  # noqa: E501


        :return: The liquidreturnrate of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._liquidreturnrate

    @liquidreturnrate.setter
    def liquidreturnrate(self, liquidreturnrate):
        """Sets the liquidreturnrate of this DrillingParameterData.


        :param liquidreturnrate: The liquidreturnrate of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._liquidreturnrate = liquidreturnrate

    @property
    def note(self):
        """Gets the note of this DrillingParameterData.  # noqa: E501


        :return: The note of this DrillingParameterData.  # noqa: E501
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this DrillingParameterData.


        :param note: The note of this DrillingParameterData.  # noqa: E501
        :type: str
        """

        self._note = note

    @property
    def refnostand(self):
        """Gets the refnostand of this DrillingParameterData.  # noqa: E501


        :return: The refnostand of this DrillingParameterData.  # noqa: E501
        :rtype: str
        """
        return self._refnostand

    @refnostand.setter
    def refnostand(self, refnostand):
        """Sets the refnostand of this DrillingParameterData.


        :param refnostand: The refnostand of this DrillingParameterData.  # noqa: E501
        :type: str
        """

        self._refnostand = refnostand

    @property
    def ropinst(self):
        """Gets the ropinst of this DrillingParameterData.  # noqa: E501


        :return: The ropinst of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._ropinst

    @ropinst.setter
    def ropinst(self, ropinst):
        """Sets the ropinst of this DrillingParameterData.


        :param ropinst: The ropinst of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._ropinst = ropinst

    @property
    def rpmmotor(self):
        """Gets the rpmmotor of this DrillingParameterData.  # noqa: E501


        :return: The rpmmotor of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._rpmmotor

    @rpmmotor.setter
    def rpmmotor(self, rpmmotor):
        """Sets the rpmmotor of this DrillingParameterData.


        :param rpmmotor: The rpmmotor of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._rpmmotor = rpmmotor

    @property
    def rpmstring(self):
        """Gets the rpmstring of this DrillingParameterData.  # noqa: E501


        :return: The rpmstring of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._rpmstring

    @rpmstring.setter
    def rpmstring(self, rpmstring):
        """Sets the rpmstring of this DrillingParameterData.


        :param rpmstring: The rpmstring of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._rpmstring = rpmstring

    @property
    def sppdiff(self):
        """Gets the sppdiff of this DrillingParameterData.  # noqa: E501


        :return: The sppdiff of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._sppdiff

    @sppdiff.setter
    def sppdiff(self, sppdiff):
        """Sets the sppdiff of this DrillingParameterData.


        :param sppdiff: The sppdiff of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._sppdiff = sppdiff

    @property
    def sppdrill(self):
        """Gets the sppdrill of this DrillingParameterData.  # noqa: E501


        :return: The sppdrill of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._sppdrill

    @sppdrill.setter
    def sppdrill(self, sppdrill):
        """Sets the sppdrill of this DrillingParameterData.


        :param sppdrill: The sppdrill of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._sppdrill = sppdrill

    @property
    def surfannpres(self):
        """Gets the surfannpres of this DrillingParameterData.  # noqa: E501


        :return: The surfannpres of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._surfannpres

    @surfannpres.setter
    def surfannpres(self, surfannpres):
        """Sets the surfannpres of this DrillingParameterData.


        :param surfannpres: The surfannpres of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._surfannpres = surfannpres

    @property
    def surfanntemp(self):
        """Gets the surfanntemp of this DrillingParameterData.  # noqa: E501


        :return: The surfanntemp of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._surfanntemp

    @surfanntemp.setter
    def surfanntemp(self, surfanntemp):
        """Sets the surfanntemp of this DrillingParameterData.


        :param surfanntemp: The surfanntemp of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._surfanntemp = surfanntemp

    @property
    def szodvgstab(self):
        """Gets the szodvgstab of this DrillingParameterData.  # noqa: E501


        :return: The szodvgstab of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._szodvgstab

    @szodvgstab.setter
    def szodvgstab(self, szodvgstab):
        """Sets the szodvgstab of this DrillingParameterData.


        :param szodvgstab: The szodvgstab of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._szodvgstab = szodvgstab

    @property
    def tfo(self):
        """Gets the tfo of this DrillingParameterData.  # noqa: E501


        :return: The tfo of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._tfo

    @tfo.setter
    def tfo(self, tfo):
        """Sets the tfo of this DrillingParameterData.


        :param tfo: The tfo of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._tfo = tfo

    @property
    def tforef(self):
        """Gets the tforef of this DrillingParameterData.  # noqa: E501


        :return: The tforef of this DrillingParameterData.  # noqa: E501
        :rtype: str
        """
        return self._tforef

    @tforef.setter
    def tforef(self, tforef):
        """Sets the tforef of this DrillingParameterData.


        :param tforef: The tforef of this DrillingParameterData.  # noqa: E501
        :type: str
        """

        self._tforef = tforef

    @property
    def tmcirc(self):
        """Gets the tmcirc of this DrillingParameterData.  # noqa: E501


        :return: The tmcirc of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._tmcirc

    @tmcirc.setter
    def tmcirc(self, tmcirc):
        """Sets the tmcirc of this DrillingParameterData.


        :param tmcirc: The tmcirc of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._tmcirc = tmcirc

    @property
    def tmdrill(self):
        """Gets the tmdrill of this DrillingParameterData.  # noqa: E501


        :return: The tmdrill of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._tmdrill

    @tmdrill.setter
    def tmdrill(self, tmdrill):
        """Sets the tmdrill of this DrillingParameterData.


        :param tmdrill: The tmdrill of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._tmdrill = tmdrill

    @property
    def tmother(self):
        """Gets the tmother of this DrillingParameterData.  # noqa: E501


        :return: The tmother of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._tmother

    @tmother.setter
    def tmother(self, tmother):
        """Sets the tmother of this DrillingParameterData.


        :param tmother: The tmother of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._tmother = tmother

    @property
    def tmtrip(self):
        """Gets the tmtrip of this DrillingParameterData.  # noqa: E501


        :return: The tmtrip of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._tmtrip

    @tmtrip.setter
    def tmtrip(self, tmtrip):
        """Sets the tmtrip of this DrillingParameterData.


        :param tmtrip: The tmtrip of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._tmtrip = tmtrip

    @property
    def torquedrill(self):
        """Gets the torquedrill of this DrillingParameterData.  # noqa: E501


        :return: The torquedrill of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._torquedrill

    @torquedrill.setter
    def torquedrill(self, torquedrill):
        """Sets the torquedrill of this DrillingParameterData.


        :param torquedrill: The torquedrill of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._torquedrill = torquedrill

    @property
    def torqueoffbtm(self):
        """Gets the torqueoffbtm of this DrillingParameterData.  # noqa: E501


        :return: The torqueoffbtm of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._torqueoffbtm

    @torqueoffbtm.setter
    def torqueoffbtm(self, torqueoffbtm):
        """Sets the torqueoffbtm of this DrillingParameterData.


        :param torqueoffbtm: The torqueoffbtm of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._torqueoffbtm = torqueoffbtm

    @property
    def torqueunits(self):
        """Gets the torqueunits of this DrillingParameterData.  # noqa: E501


        :return: The torqueunits of this DrillingParameterData.  # noqa: E501
        :rtype: str
        """
        return self._torqueunits

    @torqueunits.setter
    def torqueunits(self, torqueunits):
        """Sets the torqueunits of this DrillingParameterData.


        :param torqueunits: The torqueunits of this DrillingParameterData.  # noqa: E501
        :type: str
        """

        self._torqueunits = torqueunits

    @property
    def typ1(self):
        """Gets the typ1 of this DrillingParameterData.  # noqa: E501


        :return: The typ1 of this DrillingParameterData.  # noqa: E501
        :rtype: str
        """
        return self._typ1

    @typ1.setter
    def typ1(self, typ1):
        """Sets the typ1 of this DrillingParameterData.


        :param typ1: The typ1 of this DrillingParameterData.  # noqa: E501
        :type: str
        """

        self._typ1 = typ1

    @property
    def typ2(self):
        """Gets the typ2 of this DrillingParameterData.  # noqa: E501


        :return: The typ2 of this DrillingParameterData.  # noqa: E501
        :rtype: str
        """
        return self._typ2

    @typ2.setter
    def typ2(self, typ2):
        """Sets the typ2 of this DrillingParameterData.


        :param typ2: The typ2 of this DrillingParameterData.  # noqa: E501
        :type: str
        """

        self._typ2 = typ2

    @property
    def wob(self):
        """Gets the wob of this DrillingParameterData.  # noqa: E501


        :return: The wob of this DrillingParameterData.  # noqa: E501
        :rtype: float
        """
        return self._wob

    @wob.setter
    def wob(self, wob):
        """Sets the wob of this DrillingParameterData.


        :param wob: The wob of this DrillingParameterData.  # noqa: E501
        :type: float
        """

        self._wob = wob

    @property
    def systag(self):
        """Gets the systag of this DrillingParameterData.  # noqa: E501


        :return: The systag of this DrillingParameterData.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this DrillingParameterData.


        :param systag: The systag of this DrillingParameterData.  # noqa: E501
        :type: str
        """

        self._systag = systag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DrillingParameterData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DrillingParameterData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
