# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RFTGaugesData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dttmcalibrate': 'datetime',
        'idrec': 'str',
        'idrecparent': 'str',
        'idwell': 'str',
        'presref': 'str',
        'sn': 'str',
        'typ': 'str',
        'systag': 'str'
    }

    attribute_map = {
        'dttmcalibrate': 'dttmcalibrate',
        'idrec': 'idrec',
        'idrecparent': 'idrecparent',
        'idwell': 'idwell',
        'presref': 'presref',
        'sn': 'sn',
        'typ': 'typ',
        'systag': 'systag'
    }

    def __init__(self, dttmcalibrate=None, idrec=None, idrecparent=None, idwell=None, presref=None, sn=None, typ=None, systag=None):  # noqa: E501
        """RFTGaugesData - a model defined in Swagger"""  # noqa: E501
        self._dttmcalibrate = None
        self._idrec = None
        self._idrecparent = None
        self._idwell = None
        self._presref = None
        self._sn = None
        self._typ = None
        self._systag = None
        self.discriminator = None
        if dttmcalibrate is not None:
            self.dttmcalibrate = dttmcalibrate
        if idrec is not None:
            self.idrec = idrec
        self.idrecparent = idrecparent
        self.idwell = idwell
        if presref is not None:
            self.presref = presref
        if sn is not None:
            self.sn = sn
        if typ is not None:
            self.typ = typ
        if systag is not None:
            self.systag = systag

    @property
    def dttmcalibrate(self):
        """Gets the dttmcalibrate of this RFTGaugesData.  # noqa: E501


        :return: The dttmcalibrate of this RFTGaugesData.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmcalibrate

    @dttmcalibrate.setter
    def dttmcalibrate(self, dttmcalibrate):
        """Sets the dttmcalibrate of this RFTGaugesData.


        :param dttmcalibrate: The dttmcalibrate of this RFTGaugesData.  # noqa: E501
        :type: datetime
        """

        self._dttmcalibrate = dttmcalibrate

    @property
    def idrec(self):
        """Gets the idrec of this RFTGaugesData.  # noqa: E501

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :return: The idrec of this RFTGaugesData.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this RFTGaugesData.

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :param idrec: The idrec of this RFTGaugesData.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idrecparent(self):
        """Gets the idrecparent of this RFTGaugesData.  # noqa: E501

        id of parrent table  # noqa: E501

        :return: The idrecparent of this RFTGaugesData.  # noqa: E501
        :rtype: str
        """
        return self._idrecparent

    @idrecparent.setter
    def idrecparent(self, idrecparent):
        """Sets the idrecparent of this RFTGaugesData.

        id of parrent table  # noqa: E501

        :param idrecparent: The idrecparent of this RFTGaugesData.  # noqa: E501
        :type: str
        """
        if idrecparent is None:
            raise ValueError("Invalid value for `idrecparent`, must not be `None`")  # noqa: E501

        self._idrecparent = idrecparent

    @property
    def idwell(self):
        """Gets the idwell of this RFTGaugesData.  # noqa: E501

        id of well  # noqa: E501

        :return: The idwell of this RFTGaugesData.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this RFTGaugesData.

        id of well  # noqa: E501

        :param idwell: The idwell of this RFTGaugesData.  # noqa: E501
        :type: str
        """
        if idwell is None:
            raise ValueError("Invalid value for `idwell`, must not be `None`")  # noqa: E501

        self._idwell = idwell

    @property
    def presref(self):
        """Gets the presref of this RFTGaugesData.  # noqa: E501


        :return: The presref of this RFTGaugesData.  # noqa: E501
        :rtype: str
        """
        return self._presref

    @presref.setter
    def presref(self, presref):
        """Sets the presref of this RFTGaugesData.


        :param presref: The presref of this RFTGaugesData.  # noqa: E501
        :type: str
        """

        self._presref = presref

    @property
    def sn(self):
        """Gets the sn of this RFTGaugesData.  # noqa: E501


        :return: The sn of this RFTGaugesData.  # noqa: E501
        :rtype: str
        """
        return self._sn

    @sn.setter
    def sn(self, sn):
        """Sets the sn of this RFTGaugesData.


        :param sn: The sn of this RFTGaugesData.  # noqa: E501
        :type: str
        """

        self._sn = sn

    @property
    def typ(self):
        """Gets the typ of this RFTGaugesData.  # noqa: E501


        :return: The typ of this RFTGaugesData.  # noqa: E501
        :rtype: str
        """
        return self._typ

    @typ.setter
    def typ(self, typ):
        """Sets the typ of this RFTGaugesData.


        :param typ: The typ of this RFTGaugesData.  # noqa: E501
        :type: str
        """

        self._typ = typ

    @property
    def systag(self):
        """Gets the systag of this RFTGaugesData.  # noqa: E501


        :return: The systag of this RFTGaugesData.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this RFTGaugesData.


        :param systag: The systag of this RFTGaugesData.  # noqa: E501
        :type: str
        """

        self._systag = systag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RFTGaugesData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RFTGaugesData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
