ID_VENDOR_ID, ID_MODEL_ID, ID_VENDOR, ID_MODEL, ID_SERIAL, ID_USB_INTERFACES, ID_REVISION = \
    'ID_VENDOR_ID', 'ID_MODEL_ID', 'ID_VENDOR', 'ID_MODEL', 'ID_SERIAL', 'ID_USB_INTERFACES', 'ID_REVISION'
DEVNAME, DEVTYPE = 'DEVNAME', 'DEVTYPE'

ID_USB_CLASS_FROM_DATABASE, ID_VENDOR_FROM_DATABASE, ID_MODEL_FROM_DATABASE = \
    'ID_USB_CLASS_FROM_DATABASE', 'ID_VENDOR_FROM_DATABASE', 'ID_MODEL_FROM_DATABASE'