__version__ = "0.0.3"

from typing_extensions import Self

from . import mask  # noqa: F401  # pyright: ignore[reportUnusedImport]
from .anns import Annotation, Category, Image

class COCO:
    def __init__(self: Self, annotation_path: str, image_folder_path: str) -> None: ...
    def get_ann(self: Self, ann_id: int) -> Annotation: ...
    def get_anns(self: Self) -> list[Annotation]: ...
    def get_cat(self: Self, cat_id: int) -> Category: ...
    def get_cats(self: Self) -> list[Category]: ...
    def get_img(self: Self, img_id: int) -> Image: ...
    def get_imgs(self: Self) -> list[Image]: ...
    def get_img_anns(self: Self, img_id: int) -> list[Annotation]: ...
    def visualize_img(self: Self, img_id: int) -> None: ...
