
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-27T10:55:08-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "d055fb41c54a53dcb83ad97cb9ee280753154dd3",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
