# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AgreementData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'com': 'str',
        'contractno': 'str',
        'des': 'str',
        'dttmend': 'datetime',
        'dttmstart': 'datetime',
        'dttmstatus': 'datetime',
        'idrec': 'str',
        'idwell': 'str',
        'refno': 'str',
        'status': 'str',
        'typ1': 'str',
        'typ2': 'str',
        'systag': 'str'
    }

    attribute_map = {
        'com': 'com',
        'contractno': 'contractno',
        'des': 'des',
        'dttmend': 'dttmend',
        'dttmstart': 'dttmstart',
        'dttmstatus': 'dttmstatus',
        'idrec': 'idrec',
        'idwell': 'idwell',
        'refno': 'refno',
        'status': 'status',
        'typ1': 'typ1',
        'typ2': 'typ2',
        'systag': 'systag'
    }

    def __init__(self, com=None, contractno=None, des=None, dttmend=None, dttmstart=None, dttmstatus=None, idrec=None, idwell=None, refno=None, status=None, typ1=None, typ2=None, systag=None):  # noqa: E501
        """AgreementData - a model defined in Swagger"""  # noqa: E501
        self._com = None
        self._contractno = None
        self._des = None
        self._dttmend = None
        self._dttmstart = None
        self._dttmstatus = None
        self._idrec = None
        self._idwell = None
        self._refno = None
        self._status = None
        self._typ1 = None
        self._typ2 = None
        self._systag = None
        self.discriminator = None
        if com is not None:
            self.com = com
        if contractno is not None:
            self.contractno = contractno
        if des is not None:
            self.des = des
        if dttmend is not None:
            self.dttmend = dttmend
        if dttmstart is not None:
            self.dttmstart = dttmstart
        if dttmstatus is not None:
            self.dttmstatus = dttmstatus
        if idrec is not None:
            self.idrec = idrec
        self.idwell = idwell
        if refno is not None:
            self.refno = refno
        if status is not None:
            self.status = status
        if typ1 is not None:
            self.typ1 = typ1
        if typ2 is not None:
            self.typ2 = typ2
        if systag is not None:
            self.systag = systag

    @property
    def com(self):
        """Gets the com of this AgreementData.  # noqa: E501


        :return: The com of this AgreementData.  # noqa: E501
        :rtype: str
        """
        return self._com

    @com.setter
    def com(self, com):
        """Sets the com of this AgreementData.


        :param com: The com of this AgreementData.  # noqa: E501
        :type: str
        """

        self._com = com

    @property
    def contractno(self):
        """Gets the contractno of this AgreementData.  # noqa: E501


        :return: The contractno of this AgreementData.  # noqa: E501
        :rtype: str
        """
        return self._contractno

    @contractno.setter
    def contractno(self, contractno):
        """Sets the contractno of this AgreementData.


        :param contractno: The contractno of this AgreementData.  # noqa: E501
        :type: str
        """

        self._contractno = contractno

    @property
    def des(self):
        """Gets the des of this AgreementData.  # noqa: E501


        :return: The des of this AgreementData.  # noqa: E501
        :rtype: str
        """
        return self._des

    @des.setter
    def des(self, des):
        """Sets the des of this AgreementData.


        :param des: The des of this AgreementData.  # noqa: E501
        :type: str
        """

        self._des = des

    @property
    def dttmend(self):
        """Gets the dttmend of this AgreementData.  # noqa: E501


        :return: The dttmend of this AgreementData.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmend

    @dttmend.setter
    def dttmend(self, dttmend):
        """Sets the dttmend of this AgreementData.


        :param dttmend: The dttmend of this AgreementData.  # noqa: E501
        :type: datetime
        """

        self._dttmend = dttmend

    @property
    def dttmstart(self):
        """Gets the dttmstart of this AgreementData.  # noqa: E501


        :return: The dttmstart of this AgreementData.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmstart

    @dttmstart.setter
    def dttmstart(self, dttmstart):
        """Sets the dttmstart of this AgreementData.


        :param dttmstart: The dttmstart of this AgreementData.  # noqa: E501
        :type: datetime
        """

        self._dttmstart = dttmstart

    @property
    def dttmstatus(self):
        """Gets the dttmstatus of this AgreementData.  # noqa: E501


        :return: The dttmstatus of this AgreementData.  # noqa: E501
        :rtype: datetime
        """
        return self._dttmstatus

    @dttmstatus.setter
    def dttmstatus(self, dttmstatus):
        """Sets the dttmstatus of this AgreementData.


        :param dttmstatus: The dttmstatus of this AgreementData.  # noqa: E501
        :type: datetime
        """

        self._dttmstatus = dttmstatus

    @property
    def idrec(self):
        """Gets the idrec of this AgreementData.  # noqa: E501

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :return: The idrec of this AgreementData.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this AgreementData.

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :param idrec: The idrec of this AgreementData.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idwell(self):
        """Gets the idwell of this AgreementData.  # noqa: E501

        id of well  # noqa: E501

        :return: The idwell of this AgreementData.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this AgreementData.

        id of well  # noqa: E501

        :param idwell: The idwell of this AgreementData.  # noqa: E501
        :type: str
        """
        if idwell is None:
            raise ValueError("Invalid value for `idwell`, must not be `None`")  # noqa: E501

        self._idwell = idwell

    @property
    def refno(self):
        """Gets the refno of this AgreementData.  # noqa: E501


        :return: The refno of this AgreementData.  # noqa: E501
        :rtype: str
        """
        return self._refno

    @refno.setter
    def refno(self, refno):
        """Sets the refno of this AgreementData.


        :param refno: The refno of this AgreementData.  # noqa: E501
        :type: str
        """

        self._refno = refno

    @property
    def status(self):
        """Gets the status of this AgreementData.  # noqa: E501


        :return: The status of this AgreementData.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this AgreementData.


        :param status: The status of this AgreementData.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def typ1(self):
        """Gets the typ1 of this AgreementData.  # noqa: E501


        :return: The typ1 of this AgreementData.  # noqa: E501
        :rtype: str
        """
        return self._typ1

    @typ1.setter
    def typ1(self, typ1):
        """Sets the typ1 of this AgreementData.


        :param typ1: The typ1 of this AgreementData.  # noqa: E501
        :type: str
        """

        self._typ1 = typ1

    @property
    def typ2(self):
        """Gets the typ2 of this AgreementData.  # noqa: E501


        :return: The typ2 of this AgreementData.  # noqa: E501
        :rtype: str
        """
        return self._typ2

    @typ2.setter
    def typ2(self, typ2):
        """Sets the typ2 of this AgreementData.


        :param typ2: The typ2 of this AgreementData.  # noqa: E501
        :type: str
        """

        self._typ2 = typ2

    @property
    def systag(self):
        """Gets the systag of this AgreementData.  # noqa: E501


        :return: The systag of this AgreementData.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this AgreementData.


        :param systag: The systag of this AgreementData.  # noqa: E501
        :type: str
        """

        self._systag = systag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AgreementData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AgreementData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
