# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OfflineActivityTimeLogData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'affectonline': 'str',
        'code1': 'str',
        'code2': 'str',
        'code3': 'str',
        'code4': 'str',
        'com': 'str',
        'depthend': 'float',
        'depthstart': 'float',
        'duration': 'float',
        'idrec': 'str',
        'idrecparent': 'str',
        'idrecwellbore': 'str',
        'idwell': 'str',
        'inactive': 'bool',
        'opscategory': 'str',
        'refderrick': 'str',
        'unschedtyp': 'str',
        'usertxt1': 'str',
        'systag': 'str'
    }

    attribute_map = {
        'affectonline': 'affectonline',
        'code1': 'code1',
        'code2': 'code2',
        'code3': 'code3',
        'code4': 'code4',
        'com': 'com',
        'depthend': 'depthend',
        'depthstart': 'depthstart',
        'duration': 'duration',
        'idrec': 'idrec',
        'idrecparent': 'idrecparent',
        'idrecwellbore': 'idrecwellbore',
        'idwell': 'idwell',
        'inactive': 'inactive',
        'opscategory': 'opscategory',
        'refderrick': 'refderrick',
        'unschedtyp': 'unschedtyp',
        'usertxt1': 'usertxt1',
        'systag': 'systag'
    }

    def __init__(self, affectonline=None, code1=None, code2=None, code3=None, code4=None, com=None, depthend=None, depthstart=None, duration=None, idrec=None, idrecparent=None, idrecwellbore=None, idwell=None, inactive=None, opscategory=None, refderrick=None, unschedtyp=None, usertxt1=None, systag=None):  # noqa: E501
        """OfflineActivityTimeLogData - a model defined in Swagger"""  # noqa: E501
        self._affectonline = None
        self._code1 = None
        self._code2 = None
        self._code3 = None
        self._code4 = None
        self._com = None
        self._depthend = None
        self._depthstart = None
        self._duration = None
        self._idrec = None
        self._idrecparent = None
        self._idrecwellbore = None
        self._idwell = None
        self._inactive = None
        self._opscategory = None
        self._refderrick = None
        self._unschedtyp = None
        self._usertxt1 = None
        self._systag = None
        self.discriminator = None
        if affectonline is not None:
            self.affectonline = affectonline
        if code1 is not None:
            self.code1 = code1
        if code2 is not None:
            self.code2 = code2
        if code3 is not None:
            self.code3 = code3
        if code4 is not None:
            self.code4 = code4
        if com is not None:
            self.com = com
        if depthend is not None:
            self.depthend = depthend
        if depthstart is not None:
            self.depthstart = depthstart
        if duration is not None:
            self.duration = duration
        if idrec is not None:
            self.idrec = idrec
        self.idrecparent = idrecparent
        if idrecwellbore is not None:
            self.idrecwellbore = idrecwellbore
        self.idwell = idwell
        if inactive is not None:
            self.inactive = inactive
        if opscategory is not None:
            self.opscategory = opscategory
        if refderrick is not None:
            self.refderrick = refderrick
        if unschedtyp is not None:
            self.unschedtyp = unschedtyp
        if usertxt1 is not None:
            self.usertxt1 = usertxt1
        if systag is not None:
            self.systag = systag

    @property
    def affectonline(self):
        """Gets the affectonline of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The affectonline of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._affectonline

    @affectonline.setter
    def affectonline(self, affectonline):
        """Sets the affectonline of this OfflineActivityTimeLogData.


        :param affectonline: The affectonline of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """

        self._affectonline = affectonline

    @property
    def code1(self):
        """Gets the code1 of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The code1 of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._code1

    @code1.setter
    def code1(self, code1):
        """Sets the code1 of this OfflineActivityTimeLogData.


        :param code1: The code1 of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """

        self._code1 = code1

    @property
    def code2(self):
        """Gets the code2 of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The code2 of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._code2

    @code2.setter
    def code2(self, code2):
        """Sets the code2 of this OfflineActivityTimeLogData.


        :param code2: The code2 of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """

        self._code2 = code2

    @property
    def code3(self):
        """Gets the code3 of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The code3 of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._code3

    @code3.setter
    def code3(self, code3):
        """Sets the code3 of this OfflineActivityTimeLogData.


        :param code3: The code3 of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """

        self._code3 = code3

    @property
    def code4(self):
        """Gets the code4 of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The code4 of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._code4

    @code4.setter
    def code4(self, code4):
        """Sets the code4 of this OfflineActivityTimeLogData.


        :param code4: The code4 of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """

        self._code4 = code4

    @property
    def com(self):
        """Gets the com of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The com of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._com

    @com.setter
    def com(self, com):
        """Sets the com of this OfflineActivityTimeLogData.


        :param com: The com of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """

        self._com = com

    @property
    def depthend(self):
        """Gets the depthend of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The depthend of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: float
        """
        return self._depthend

    @depthend.setter
    def depthend(self, depthend):
        """Sets the depthend of this OfflineActivityTimeLogData.


        :param depthend: The depthend of this OfflineActivityTimeLogData.  # noqa: E501
        :type: float
        """

        self._depthend = depthend

    @property
    def depthstart(self):
        """Gets the depthstart of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The depthstart of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: float
        """
        return self._depthstart

    @depthstart.setter
    def depthstart(self, depthstart):
        """Sets the depthstart of this OfflineActivityTimeLogData.


        :param depthstart: The depthstart of this OfflineActivityTimeLogData.  # noqa: E501
        :type: float
        """

        self._depthstart = depthstart

    @property
    def duration(self):
        """Gets the duration of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The duration of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: float
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this OfflineActivityTimeLogData.


        :param duration: The duration of this OfflineActivityTimeLogData.  # noqa: E501
        :type: float
        """

        self._duration = duration

    @property
    def idrec(self):
        """Gets the idrec of this OfflineActivityTimeLogData.  # noqa: E501

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :return: The idrec of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this OfflineActivityTimeLogData.

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :param idrec: The idrec of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idrecparent(self):
        """Gets the idrecparent of this OfflineActivityTimeLogData.  # noqa: E501

        id of parrent table  # noqa: E501

        :return: The idrecparent of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._idrecparent

    @idrecparent.setter
    def idrecparent(self, idrecparent):
        """Sets the idrecparent of this OfflineActivityTimeLogData.

        id of parrent table  # noqa: E501

        :param idrecparent: The idrecparent of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """
        if idrecparent is None:
            raise ValueError("Invalid value for `idrecparent`, must not be `None`")  # noqa: E501

        self._idrecparent = idrecparent

    @property
    def idrecwellbore(self):
        """Gets the idrecwellbore of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The idrecwellbore of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._idrecwellbore

    @idrecwellbore.setter
    def idrecwellbore(self, idrecwellbore):
        """Sets the idrecwellbore of this OfflineActivityTimeLogData.


        :param idrecwellbore: The idrecwellbore of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """

        self._idrecwellbore = idrecwellbore

    @property
    def idwell(self):
        """Gets the idwell of this OfflineActivityTimeLogData.  # noqa: E501

        id of well  # noqa: E501

        :return: The idwell of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this OfflineActivityTimeLogData.

        id of well  # noqa: E501

        :param idwell: The idwell of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """
        if idwell is None:
            raise ValueError("Invalid value for `idwell`, must not be `None`")  # noqa: E501

        self._idwell = idwell

    @property
    def inactive(self):
        """Gets the inactive of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The inactive of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: bool
        """
        return self._inactive

    @inactive.setter
    def inactive(self, inactive):
        """Sets the inactive of this OfflineActivityTimeLogData.


        :param inactive: The inactive of this OfflineActivityTimeLogData.  # noqa: E501
        :type: bool
        """

        self._inactive = inactive

    @property
    def opscategory(self):
        """Gets the opscategory of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The opscategory of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._opscategory

    @opscategory.setter
    def opscategory(self, opscategory):
        """Sets the opscategory of this OfflineActivityTimeLogData.


        :param opscategory: The opscategory of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """

        self._opscategory = opscategory

    @property
    def refderrick(self):
        """Gets the refderrick of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The refderrick of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._refderrick

    @refderrick.setter
    def refderrick(self, refderrick):
        """Sets the refderrick of this OfflineActivityTimeLogData.


        :param refderrick: The refderrick of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """

        self._refderrick = refderrick

    @property
    def unschedtyp(self):
        """Gets the unschedtyp of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The unschedtyp of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._unschedtyp

    @unschedtyp.setter
    def unschedtyp(self, unschedtyp):
        """Sets the unschedtyp of this OfflineActivityTimeLogData.


        :param unschedtyp: The unschedtyp of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """

        self._unschedtyp = unschedtyp

    @property
    def usertxt1(self):
        """Gets the usertxt1 of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The usertxt1 of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._usertxt1

    @usertxt1.setter
    def usertxt1(self, usertxt1):
        """Sets the usertxt1 of this OfflineActivityTimeLogData.


        :param usertxt1: The usertxt1 of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """

        self._usertxt1 = usertxt1

    @property
    def systag(self):
        """Gets the systag of this OfflineActivityTimeLogData.  # noqa: E501


        :return: The systag of this OfflineActivityTimeLogData.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this OfflineActivityTimeLogData.


        :param systag: The systag of this OfflineActivityTimeLogData.  # noqa: E501
        :type: str
        """

        self._systag = systag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OfflineActivityTimeLogData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OfflineActivityTimeLogData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
