# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SlottedLinerLinerScreenData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'blankbottom': 'float',
        'blanktop': 'float',
        'centerslengthwise': 'float',
        'idrec': 'str',
        'idrecparent': 'str',
        'idwell': 'str',
        'openingmaxdimension': 'float',
        'openingmindimension': 'float',
        'percentopenarea': 'float',
        'perfrows': 'int',
        'screengauge': 'float',
        'slotdes': 'str',
        'slotfrequency': 'float',
        'slotlength': 'float',
        'slotpattern': 'str',
        'slotwidth': 'float',
        'systag': 'str'
    }

    attribute_map = {
        'blankbottom': 'blankbottom',
        'blanktop': 'blanktop',
        'centerslengthwise': 'centerslengthwise',
        'idrec': 'idrec',
        'idrecparent': 'idrecparent',
        'idwell': 'idwell',
        'openingmaxdimension': 'openingmaxdimension',
        'openingmindimension': 'openingmindimension',
        'percentopenarea': 'percentopenarea',
        'perfrows': 'perfrows',
        'screengauge': 'screengauge',
        'slotdes': 'slotdes',
        'slotfrequency': 'slotfrequency',
        'slotlength': 'slotlength',
        'slotpattern': 'slotpattern',
        'slotwidth': 'slotwidth',
        'systag': 'systag'
    }

    def __init__(self, blankbottom=None, blanktop=None, centerslengthwise=None, idrec=None, idrecparent=None, idwell=None, openingmaxdimension=None, openingmindimension=None, percentopenarea=None, perfrows=None, screengauge=None, slotdes=None, slotfrequency=None, slotlength=None, slotpattern=None, slotwidth=None, systag=None):  # noqa: E501
        """SlottedLinerLinerScreenData - a model defined in Swagger"""  # noqa: E501
        self._blankbottom = None
        self._blanktop = None
        self._centerslengthwise = None
        self._idrec = None
        self._idrecparent = None
        self._idwell = None
        self._openingmaxdimension = None
        self._openingmindimension = None
        self._percentopenarea = None
        self._perfrows = None
        self._screengauge = None
        self._slotdes = None
        self._slotfrequency = None
        self._slotlength = None
        self._slotpattern = None
        self._slotwidth = None
        self._systag = None
        self.discriminator = None
        if blankbottom is not None:
            self.blankbottom = blankbottom
        if blanktop is not None:
            self.blanktop = blanktop
        if centerslengthwise is not None:
            self.centerslengthwise = centerslengthwise
        if idrec is not None:
            self.idrec = idrec
        self.idrecparent = idrecparent
        self.idwell = idwell
        if openingmaxdimension is not None:
            self.openingmaxdimension = openingmaxdimension
        if openingmindimension is not None:
            self.openingmindimension = openingmindimension
        if percentopenarea is not None:
            self.percentopenarea = percentopenarea
        if perfrows is not None:
            self.perfrows = perfrows
        if screengauge is not None:
            self.screengauge = screengauge
        if slotdes is not None:
            self.slotdes = slotdes
        if slotfrequency is not None:
            self.slotfrequency = slotfrequency
        if slotlength is not None:
            self.slotlength = slotlength
        if slotpattern is not None:
            self.slotpattern = slotpattern
        if slotwidth is not None:
            self.slotwidth = slotwidth
        if systag is not None:
            self.systag = systag

    @property
    def blankbottom(self):
        """Gets the blankbottom of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The blankbottom of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: float
        """
        return self._blankbottom

    @blankbottom.setter
    def blankbottom(self, blankbottom):
        """Sets the blankbottom of this SlottedLinerLinerScreenData.


        :param blankbottom: The blankbottom of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: float
        """

        self._blankbottom = blankbottom

    @property
    def blanktop(self):
        """Gets the blanktop of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The blanktop of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: float
        """
        return self._blanktop

    @blanktop.setter
    def blanktop(self, blanktop):
        """Sets the blanktop of this SlottedLinerLinerScreenData.


        :param blanktop: The blanktop of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: float
        """

        self._blanktop = blanktop

    @property
    def centerslengthwise(self):
        """Gets the centerslengthwise of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The centerslengthwise of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: float
        """
        return self._centerslengthwise

    @centerslengthwise.setter
    def centerslengthwise(self, centerslengthwise):
        """Sets the centerslengthwise of this SlottedLinerLinerScreenData.


        :param centerslengthwise: The centerslengthwise of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: float
        """

        self._centerslengthwise = centerslengthwise

    @property
    def idrec(self):
        """Gets the idrec of this SlottedLinerLinerScreenData.  # noqa: E501

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :return: The idrec of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this SlottedLinerLinerScreenData.

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :param idrec: The idrec of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idrecparent(self):
        """Gets the idrecparent of this SlottedLinerLinerScreenData.  # noqa: E501

        id of parrent table  # noqa: E501

        :return: The idrecparent of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: str
        """
        return self._idrecparent

    @idrecparent.setter
    def idrecparent(self, idrecparent):
        """Sets the idrecparent of this SlottedLinerLinerScreenData.

        id of parrent table  # noqa: E501

        :param idrecparent: The idrecparent of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: str
        """
        if idrecparent is None:
            raise ValueError("Invalid value for `idrecparent`, must not be `None`")  # noqa: E501

        self._idrecparent = idrecparent

    @property
    def idwell(self):
        """Gets the idwell of this SlottedLinerLinerScreenData.  # noqa: E501

        id of well  # noqa: E501

        :return: The idwell of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this SlottedLinerLinerScreenData.

        id of well  # noqa: E501

        :param idwell: The idwell of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: str
        """
        if idwell is None:
            raise ValueError("Invalid value for `idwell`, must not be `None`")  # noqa: E501

        self._idwell = idwell

    @property
    def openingmaxdimension(self):
        """Gets the openingmaxdimension of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The openingmaxdimension of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: float
        """
        return self._openingmaxdimension

    @openingmaxdimension.setter
    def openingmaxdimension(self, openingmaxdimension):
        """Sets the openingmaxdimension of this SlottedLinerLinerScreenData.


        :param openingmaxdimension: The openingmaxdimension of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: float
        """

        self._openingmaxdimension = openingmaxdimension

    @property
    def openingmindimension(self):
        """Gets the openingmindimension of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The openingmindimension of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: float
        """
        return self._openingmindimension

    @openingmindimension.setter
    def openingmindimension(self, openingmindimension):
        """Sets the openingmindimension of this SlottedLinerLinerScreenData.


        :param openingmindimension: The openingmindimension of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: float
        """

        self._openingmindimension = openingmindimension

    @property
    def percentopenarea(self):
        """Gets the percentopenarea of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The percentopenarea of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: float
        """
        return self._percentopenarea

    @percentopenarea.setter
    def percentopenarea(self, percentopenarea):
        """Sets the percentopenarea of this SlottedLinerLinerScreenData.


        :param percentopenarea: The percentopenarea of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: float
        """

        self._percentopenarea = percentopenarea

    @property
    def perfrows(self):
        """Gets the perfrows of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The perfrows of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: int
        """
        return self._perfrows

    @perfrows.setter
    def perfrows(self, perfrows):
        """Sets the perfrows of this SlottedLinerLinerScreenData.


        :param perfrows: The perfrows of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: int
        """

        self._perfrows = perfrows

    @property
    def screengauge(self):
        """Gets the screengauge of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The screengauge of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: float
        """
        return self._screengauge

    @screengauge.setter
    def screengauge(self, screengauge):
        """Sets the screengauge of this SlottedLinerLinerScreenData.


        :param screengauge: The screengauge of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: float
        """

        self._screengauge = screengauge

    @property
    def slotdes(self):
        """Gets the slotdes of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The slotdes of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: str
        """
        return self._slotdes

    @slotdes.setter
    def slotdes(self, slotdes):
        """Sets the slotdes of this SlottedLinerLinerScreenData.


        :param slotdes: The slotdes of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: str
        """

        self._slotdes = slotdes

    @property
    def slotfrequency(self):
        """Gets the slotfrequency of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The slotfrequency of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: float
        """
        return self._slotfrequency

    @slotfrequency.setter
    def slotfrequency(self, slotfrequency):
        """Sets the slotfrequency of this SlottedLinerLinerScreenData.


        :param slotfrequency: The slotfrequency of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: float
        """

        self._slotfrequency = slotfrequency

    @property
    def slotlength(self):
        """Gets the slotlength of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The slotlength of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: float
        """
        return self._slotlength

    @slotlength.setter
    def slotlength(self, slotlength):
        """Sets the slotlength of this SlottedLinerLinerScreenData.


        :param slotlength: The slotlength of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: float
        """

        self._slotlength = slotlength

    @property
    def slotpattern(self):
        """Gets the slotpattern of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The slotpattern of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: str
        """
        return self._slotpattern

    @slotpattern.setter
    def slotpattern(self, slotpattern):
        """Sets the slotpattern of this SlottedLinerLinerScreenData.


        :param slotpattern: The slotpattern of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: str
        """

        self._slotpattern = slotpattern

    @property
    def slotwidth(self):
        """Gets the slotwidth of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The slotwidth of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: float
        """
        return self._slotwidth

    @slotwidth.setter
    def slotwidth(self, slotwidth):
        """Sets the slotwidth of this SlottedLinerLinerScreenData.


        :param slotwidth: The slotwidth of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: float
        """

        self._slotwidth = slotwidth

    @property
    def systag(self):
        """Gets the systag of this SlottedLinerLinerScreenData.  # noqa: E501


        :return: The systag of this SlottedLinerLinerScreenData.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this SlottedLinerLinerScreenData.


        :param systag: The systag of this SlottedLinerLinerScreenData.  # noqa: E501
        :type: str
        """

        self._systag = systag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SlottedLinerLinerScreenData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SlottedLinerLinerScreenData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
