from .base_keyboard import *
from .beniakoni_keyboard import *
from .berestovitsa_keyboard import *
from .brest_keyboard import *
from .grigorovshcina_keyboard import *
from .kamenny_log_keyboard import *
from .kotlovka_keyboard import *
from .urbany_keyboard import *
from .monitoring_keyboard import *
