
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-23T11:40:40-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e110b9d127a0f8f1455ae3926b32d29422363e1",
 "version": "0.11.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
