from django.contrib import admin
from .models import *

admin.site.register(Objective)
admin.site.register(Position)
admin.site.register(Aspect)
admin.site.register(AspectOps)
admin.site.register(Diploma)
admin.site.register(Plan)
admin.site.register(PlanTrack)
admin.site.register(PlanPos)
admin.site.register(PlanPosAspect)
admin.site.register(TeamPos)
admin.site.register(Painel)
admin.site.register(Schedule)
admin.site.register(Candidate)
admin.site.register(CandScore)
admin.site.register(CandShortList)
admin.site.register(CandWritten)
admin.site.register(CandOral)
admin.site.register(PlanUnit)
admin.site.register(ShortListType)
admin.site.register(CandidateCv)
admin.site.register(CandidateShorListSum)
admin.site.register(PlanAttach)