# Generated by Django 3.2 on 2022-12-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20221211_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripemp',
            name='is_update',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Update Absensia'),
        ),
    ]
