# Generated by Django 4.0 on 2022-12-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment2', '0008_rename_score_candshortlist_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candshortlist',
            old_name='comment',
            new_name='comment_a',
        ),
        migrations.AddField(
            model_name='candshortlist',
            name='comment_b',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Komentariu'),
        ),
        migrations.AddField(
            model_name='candshortlist',
            name='comment_c',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Komentariu'),
        ),
        migrations.AddField(
            model_name='candshortlist',
            name='comment_d',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Komentariu'),
        ),
    ]
