# Generated by Django 4.0 on 2022-12-08 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment2', '0009_rename_comment_candshortlist_comment_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painel',
            name='plan_pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='painel', to='recruitment2.planpos'),
        ),
    ]
