# Generated by Django 3.2 on 2023-02-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment2', '0025_auto_20230215_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpos',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vacancy Tracking Number'),
        ),
    ]
