
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-28T22:06:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1bf9718ebcac39a6db47d4eb430b3a19896a8be6",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
