
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-03-29T04:38:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "39e98fcffaf55f7ac089efab2e5200f22bd659a2",
 "version": "1.18.2.post0.dev317"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
