VERSION_YEAR = 2023
VERSION_MONTH = int('03')
VERSION_DAY = int('25')
VERSION_HOUR = int('18')
VERSION_MINUTE = int('20')
MAJOR_VERSION = 1
MINOR_VERSION = 3
PATCH_VERSION = 202303251820
version_date = '2023/03/25 18:20'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
