# Generated by Django 4.0 on 2022-12-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='is_confirm',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='is_lock',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
