# Generated by Django 4.0 on 2022-09-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_rename_section_contract_department_and_more'),
        ('custom', '0002_rename_section_dep_rename_department_studyprogram_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dep',
            new_name='Department',
        ),
    ]
