# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_sdk_api
from wellview_sdk_api.models.risers_diverter_data import RisersDiverterData  # noqa: E501
from wellview_sdk_api.rest import ApiException


class TestRisersDiverterData(unittest.TestCase):
    """RisersDiverterData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRisersDiverterData(self):
        """Test RisersDiverterData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = wellview_sdk_api.models.risers_diverter_data.RisersDiverterData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
