# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_sdk_api
from wellview_sdk_api.models.phase_risk_impact_data import PhaseRiskImpactData  # noqa: E501
from wellview_sdk_api.rest import ApiException


class TestPhaseRiskImpactData(unittest.TestCase):
    """PhaseRiskImpactData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPhaseRiskImpactData(self):
        """Test PhaseRiskImpactData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = wellview_sdk_api.models.phase_risk_impact_data.PhaseRiskImpactData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
