# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PolishRodData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'com': 'str',
        'idrec': 'str',
        'idrecparent': 'str',
        'idwell': 'str',
        'lengthpolishrodlnr': 'float',
        'materialpolishrodlnr': 'str',
        'polishrodlnr': 'bool',
        'szodpolishrodlnr': 'float',
        'systag': 'str'
    }

    attribute_map = {
        'com': 'com',
        'idrec': 'idrec',
        'idrecparent': 'idrecparent',
        'idwell': 'idwell',
        'lengthpolishrodlnr': 'lengthpolishrodlnr',
        'materialpolishrodlnr': 'materialpolishrodlnr',
        'polishrodlnr': 'polishrodlnr',
        'szodpolishrodlnr': 'szodpolishrodlnr',
        'systag': 'systag'
    }

    def __init__(self, com=None, idrec=None, idrecparent=None, idwell=None, lengthpolishrodlnr=None, materialpolishrodlnr=None, polishrodlnr=None, szodpolishrodlnr=None, systag=None):  # noqa: E501
        """PolishRodData - a model defined in Swagger"""  # noqa: E501
        self._com = None
        self._idrec = None
        self._idrecparent = None
        self._idwell = None
        self._lengthpolishrodlnr = None
        self._materialpolishrodlnr = None
        self._polishrodlnr = None
        self._szodpolishrodlnr = None
        self._systag = None
        self.discriminator = None
        if com is not None:
            self.com = com
        if idrec is not None:
            self.idrec = idrec
        self.idrecparent = idrecparent
        self.idwell = idwell
        if lengthpolishrodlnr is not None:
            self.lengthpolishrodlnr = lengthpolishrodlnr
        if materialpolishrodlnr is not None:
            self.materialpolishrodlnr = materialpolishrodlnr
        if polishrodlnr is not None:
            self.polishrodlnr = polishrodlnr
        if szodpolishrodlnr is not None:
            self.szodpolishrodlnr = szodpolishrodlnr
        if systag is not None:
            self.systag = systag

    @property
    def com(self):
        """Gets the com of this PolishRodData.  # noqa: E501


        :return: The com of this PolishRodData.  # noqa: E501
        :rtype: str
        """
        return self._com

    @com.setter
    def com(self, com):
        """Sets the com of this PolishRodData.


        :param com: The com of this PolishRodData.  # noqa: E501
        :type: str
        """

        self._com = com

    @property
    def idrec(self):
        """Gets the idrec of this PolishRodData.  # noqa: E501

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :return: The idrec of this PolishRodData.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this PolishRodData.

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :param idrec: The idrec of this PolishRodData.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idrecparent(self):
        """Gets the idrecparent of this PolishRodData.  # noqa: E501

        id of parrent table  # noqa: E501

        :return: The idrecparent of this PolishRodData.  # noqa: E501
        :rtype: str
        """
        return self._idrecparent

    @idrecparent.setter
    def idrecparent(self, idrecparent):
        """Sets the idrecparent of this PolishRodData.

        id of parrent table  # noqa: E501

        :param idrecparent: The idrecparent of this PolishRodData.  # noqa: E501
        :type: str
        """
        if idrecparent is None:
            raise ValueError("Invalid value for `idrecparent`, must not be `None`")  # noqa: E501

        self._idrecparent = idrecparent

    @property
    def idwell(self):
        """Gets the idwell of this PolishRodData.  # noqa: E501

        id of well  # noqa: E501

        :return: The idwell of this PolishRodData.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this PolishRodData.

        id of well  # noqa: E501

        :param idwell: The idwell of this PolishRodData.  # noqa: E501
        :type: str
        """
        if idwell is None:
            raise ValueError("Invalid value for `idwell`, must not be `None`")  # noqa: E501

        self._idwell = idwell

    @property
    def lengthpolishrodlnr(self):
        """Gets the lengthpolishrodlnr of this PolishRodData.  # noqa: E501


        :return: The lengthpolishrodlnr of this PolishRodData.  # noqa: E501
        :rtype: float
        """
        return self._lengthpolishrodlnr

    @lengthpolishrodlnr.setter
    def lengthpolishrodlnr(self, lengthpolishrodlnr):
        """Sets the lengthpolishrodlnr of this PolishRodData.


        :param lengthpolishrodlnr: The lengthpolishrodlnr of this PolishRodData.  # noqa: E501
        :type: float
        """

        self._lengthpolishrodlnr = lengthpolishrodlnr

    @property
    def materialpolishrodlnr(self):
        """Gets the materialpolishrodlnr of this PolishRodData.  # noqa: E501


        :return: The materialpolishrodlnr of this PolishRodData.  # noqa: E501
        :rtype: str
        """
        return self._materialpolishrodlnr

    @materialpolishrodlnr.setter
    def materialpolishrodlnr(self, materialpolishrodlnr):
        """Sets the materialpolishrodlnr of this PolishRodData.


        :param materialpolishrodlnr: The materialpolishrodlnr of this PolishRodData.  # noqa: E501
        :type: str
        """

        self._materialpolishrodlnr = materialpolishrodlnr

    @property
    def polishrodlnr(self):
        """Gets the polishrodlnr of this PolishRodData.  # noqa: E501


        :return: The polishrodlnr of this PolishRodData.  # noqa: E501
        :rtype: bool
        """
        return self._polishrodlnr

    @polishrodlnr.setter
    def polishrodlnr(self, polishrodlnr):
        """Sets the polishrodlnr of this PolishRodData.


        :param polishrodlnr: The polishrodlnr of this PolishRodData.  # noqa: E501
        :type: bool
        """

        self._polishrodlnr = polishrodlnr

    @property
    def szodpolishrodlnr(self):
        """Gets the szodpolishrodlnr of this PolishRodData.  # noqa: E501


        :return: The szodpolishrodlnr of this PolishRodData.  # noqa: E501
        :rtype: float
        """
        return self._szodpolishrodlnr

    @szodpolishrodlnr.setter
    def szodpolishrodlnr(self, szodpolishrodlnr):
        """Sets the szodpolishrodlnr of this PolishRodData.


        :param szodpolishrodlnr: The szodpolishrodlnr of this PolishRodData.  # noqa: E501
        :type: float
        """

        self._szodpolishrodlnr = szodpolishrodlnr

    @property
    def systag(self):
        """Gets the systag of this PolishRodData.  # noqa: E501


        :return: The systag of this PolishRodData.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this PolishRodData.


        :param systag: The systag of this PolishRodData.  # noqa: E501
        :type: str
        """

        self._systag = systag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PolishRodData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PolishRodData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
