# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.9
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProppantData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'float',
        'amountdesign': 'float',
        'des': 'str',
        'idrec': 'str',
        'idrecparent': 'str',
        'idwell': 'str',
        'note': 'str',
        'sz': 'str',
        'typ1': 'str',
        'typ2': 'str',
        'usernum1': 'float',
        'usertxt1': 'str',
        'systag': 'str'
    }

    attribute_map = {
        'amount': 'amount',
        'amountdesign': 'amountdesign',
        'des': 'des',
        'idrec': 'idrec',
        'idrecparent': 'idrecparent',
        'idwell': 'idwell',
        'note': 'note',
        'sz': 'sz',
        'typ1': 'typ1',
        'typ2': 'typ2',
        'usernum1': 'usernum1',
        'usertxt1': 'usertxt1',
        'systag': 'systag'
    }

    def __init__(self, amount=None, amountdesign=None, des=None, idrec=None, idrecparent=None, idwell=None, note=None, sz=None, typ1=None, typ2=None, usernum1=None, usertxt1=None, systag=None):  # noqa: E501
        """ProppantData - a model defined in Swagger"""  # noqa: E501
        self._amount = None
        self._amountdesign = None
        self._des = None
        self._idrec = None
        self._idrecparent = None
        self._idwell = None
        self._note = None
        self._sz = None
        self._typ1 = None
        self._typ2 = None
        self._usernum1 = None
        self._usertxt1 = None
        self._systag = None
        self.discriminator = None
        if amount is not None:
            self.amount = amount
        if amountdesign is not None:
            self.amountdesign = amountdesign
        if des is not None:
            self.des = des
        if idrec is not None:
            self.idrec = idrec
        self.idrecparent = idrecparent
        self.idwell = idwell
        if note is not None:
            self.note = note
        if sz is not None:
            self.sz = sz
        if typ1 is not None:
            self.typ1 = typ1
        if typ2 is not None:
            self.typ2 = typ2
        if usernum1 is not None:
            self.usernum1 = usernum1
        if usertxt1 is not None:
            self.usertxt1 = usertxt1
        if systag is not None:
            self.systag = systag

    @property
    def amount(self):
        """Gets the amount of this ProppantData.  # noqa: E501


        :return: The amount of this ProppantData.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this ProppantData.


        :param amount: The amount of this ProppantData.  # noqa: E501
        :type: float
        """

        self._amount = amount

    @property
    def amountdesign(self):
        """Gets the amountdesign of this ProppantData.  # noqa: E501


        :return: The amountdesign of this ProppantData.  # noqa: E501
        :rtype: float
        """
        return self._amountdesign

    @amountdesign.setter
    def amountdesign(self, amountdesign):
        """Sets the amountdesign of this ProppantData.


        :param amountdesign: The amountdesign of this ProppantData.  # noqa: E501
        :type: float
        """

        self._amountdesign = amountdesign

    @property
    def des(self):
        """Gets the des of this ProppantData.  # noqa: E501


        :return: The des of this ProppantData.  # noqa: E501
        :rtype: str
        """
        return self._des

    @des.setter
    def des(self, des):
        """Sets the des of this ProppantData.


        :param des: The des of this ProppantData.  # noqa: E501
        :type: str
        """

        self._des = des

    @property
    def idrec(self):
        """Gets the idrec of this ProppantData.  # noqa: E501

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :return: The idrec of this ProppantData.  # noqa: E501
        :rtype: str
        """
        return self._idrec

    @idrec.setter
    def idrec(self, idrec):
        """Sets the idrec of this ProppantData.

        Its value is None for insert operation. It required for update and delete operations  # noqa: E501

        :param idrec: The idrec of this ProppantData.  # noqa: E501
        :type: str
        """

        self._idrec = idrec

    @property
    def idrecparent(self):
        """Gets the idrecparent of this ProppantData.  # noqa: E501

        id of parrent table  # noqa: E501

        :return: The idrecparent of this ProppantData.  # noqa: E501
        :rtype: str
        """
        return self._idrecparent

    @idrecparent.setter
    def idrecparent(self, idrecparent):
        """Sets the idrecparent of this ProppantData.

        id of parrent table  # noqa: E501

        :param idrecparent: The idrecparent of this ProppantData.  # noqa: E501
        :type: str
        """
        if idrecparent is None:
            raise ValueError("Invalid value for `idrecparent`, must not be `None`")  # noqa: E501

        self._idrecparent = idrecparent

    @property
    def idwell(self):
        """Gets the idwell of this ProppantData.  # noqa: E501

        id of well  # noqa: E501

        :return: The idwell of this ProppantData.  # noqa: E501
        :rtype: str
        """
        return self._idwell

    @idwell.setter
    def idwell(self, idwell):
        """Sets the idwell of this ProppantData.

        id of well  # noqa: E501

        :param idwell: The idwell of this ProppantData.  # noqa: E501
        :type: str
        """
        if idwell is None:
            raise ValueError("Invalid value for `idwell`, must not be `None`")  # noqa: E501

        self._idwell = idwell

    @property
    def note(self):
        """Gets the note of this ProppantData.  # noqa: E501


        :return: The note of this ProppantData.  # noqa: E501
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this ProppantData.


        :param note: The note of this ProppantData.  # noqa: E501
        :type: str
        """

        self._note = note

    @property
    def sz(self):
        """Gets the sz of this ProppantData.  # noqa: E501


        :return: The sz of this ProppantData.  # noqa: E501
        :rtype: str
        """
        return self._sz

    @sz.setter
    def sz(self, sz):
        """Sets the sz of this ProppantData.


        :param sz: The sz of this ProppantData.  # noqa: E501
        :type: str
        """

        self._sz = sz

    @property
    def typ1(self):
        """Gets the typ1 of this ProppantData.  # noqa: E501


        :return: The typ1 of this ProppantData.  # noqa: E501
        :rtype: str
        """
        return self._typ1

    @typ1.setter
    def typ1(self, typ1):
        """Sets the typ1 of this ProppantData.


        :param typ1: The typ1 of this ProppantData.  # noqa: E501
        :type: str
        """

        self._typ1 = typ1

    @property
    def typ2(self):
        """Gets the typ2 of this ProppantData.  # noqa: E501


        :return: The typ2 of this ProppantData.  # noqa: E501
        :rtype: str
        """
        return self._typ2

    @typ2.setter
    def typ2(self, typ2):
        """Sets the typ2 of this ProppantData.


        :param typ2: The typ2 of this ProppantData.  # noqa: E501
        :type: str
        """

        self._typ2 = typ2

    @property
    def usernum1(self):
        """Gets the usernum1 of this ProppantData.  # noqa: E501


        :return: The usernum1 of this ProppantData.  # noqa: E501
        :rtype: float
        """
        return self._usernum1

    @usernum1.setter
    def usernum1(self, usernum1):
        """Sets the usernum1 of this ProppantData.


        :param usernum1: The usernum1 of this ProppantData.  # noqa: E501
        :type: float
        """

        self._usernum1 = usernum1

    @property
    def usertxt1(self):
        """Gets the usertxt1 of this ProppantData.  # noqa: E501


        :return: The usertxt1 of this ProppantData.  # noqa: E501
        :rtype: str
        """
        return self._usertxt1

    @usertxt1.setter
    def usertxt1(self, usertxt1):
        """Sets the usertxt1 of this ProppantData.


        :param usertxt1: The usertxt1 of this ProppantData.  # noqa: E501
        :type: str
        """

        self._usertxt1 = usertxt1

    @property
    def systag(self):
        """Gets the systag of this ProppantData.  # noqa: E501


        :return: The systag of this ProppantData.  # noqa: E501
        :rtype: str
        """
        return self._systag

    @systag.setter
    def systag(self, systag):
        """Sets the systag of this ProppantData.


        :param systag: The systag of this ProppantData.  # noqa: E501
        :type: str
        """

        self._systag = systag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProppantData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProppantData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
