"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.geometry.v0.api_pb2
import grpc

class ApiStub:
    """Api"""
    def __init__(self, channel: grpc.Channel) -> None: ...
    SetVersion: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.api_pb2.SetVersionRequest,
        ansys.api.geometry.v0.api_pb2.SetVersionResponse] = ...
    """Sets the current scripting version."""

    GetVersion: grpc.UnaryUnaryMultiCallable[
        ansys.api.geometry.v0.api_pb2.GetVersionRequest,
        ansys.api.geometry.v0.api_pb2.GetVersionResponse] = ...
    """Sets the current scripting version."""


class ApiServicer(metaclass=abc.ABCMeta):
    """Api"""
    @abc.abstractmethod
    def SetVersion(self,
        request: ansys.api.geometry.v0.api_pb2.SetVersionRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.api_pb2.SetVersionResponse:
        """Sets the current scripting version."""
        pass

    @abc.abstractmethod
    def GetVersion(self,
        request: ansys.api.geometry.v0.api_pb2.GetVersionRequest,
        context: grpc.ServicerContext,
    ) -> ansys.api.geometry.v0.api_pb2.GetVersionResponse:
        """Sets the current scripting version."""
        pass


def add_ApiServicer_to_server(servicer: ApiServicer, server: grpc.Server) -> None: ...
