__author_email__ = 'maintainers@nullsec.space'
__description__ = 'Simple SSO library for handling OAuth2 with the EVE Online ESI API'
__license__ = 'MIT License'
__title__ = 'NanoSSO'
__url__ = 'https://github.com/NullsecSpace/NanoSSO'
__version__ = '0.1'
