# coding: utf-8

"""
    WellViewSDKAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import wellview_sdk_api
from wellview_sdk_api.models.mandrel_data import MandrelData  # noqa: E501
from wellview_sdk_api.rest import ApiException


class TestMandrelData(unittest.TestCase):
    """MandrelData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMandrelData(self):
        """Test MandrelData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = wellview_sdk_api.models.mandrel_data.MandrelData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
